### ISSUE TITLE
question: the port settings?

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#10]
i think QT5 shoud set 1080 here for socks proxy, am i right?
delete the png

**Comment by TheWanderingCoel** [comment]
No. Windows does not support socks5. That's why privoxy was introduced.

**Comment by TheWanderingCoel** [comment]
Make sure to blur your address before you send it

**Comment by babylife** [comment]
cool ,i see , thank you Sir!
