### ISSUE TITLE
PAC模式的问题

### ISSUE THREAD

**Issue by wuzhiming** [TheWanderingCoel/Trojan-Qt5#103]
1.pac模式的勾选，界面太深了，能不能弄到小图标的右键菜单？
![image](https://user-images.githubusercontent.com/6093737/75406213-dbe6a800-594a-11ea-861d-3363ac84e71e.png)
2.貌似每次切换是否打开pac模式，都要重新连下服务器才能生效，这个能不能立即生效呢？

**Comment by TheWanderingCoel** [comment]
1. 0.0.4版本会增加。
2. 这个可以考虑下。需要点时间

**Comment by TheWanderingCoel** [comment]
已完全实现

**Comment by wuzhiming** [comment]
给兄弟点个赞，立即生效这个东西太有用了-。-
