### ISSUE TITLE
安卓的电视是否可以适配

### ISSUE THREAD

**Issue by johnsterkong** [TheWanderingCoel/Trojan-Qt5#110]
还是想发在电视上用，又不想刷路由器。谢谢！

**Comment by TheWanderingCoel** [comment]
请尝试使用igniter

**Comment by MintBlue** [comment]
> 请尝试使用igniter
你好，可以像ss一样，允许局域网其他设备接入吗？

**Comment by TheWanderingCoel** [comment]
igniter么，问问trojan-gfw吧。毕竟不是我写的

**Comment by MintBlue** [comment]
> igniter么，问问trojan-gfw吧。毕竟不是我写的


谢谢回复，不是igniter，就是Trojan-Qt5。
pc端ss可以允许局域网其他设备接入，比如switch，Trojan-Qt5现在可以么

**Comment by johnsterkong** [comment]
> igniter么，问问trojan-gfw吧。毕竟不是我写的

谢谢！

**Comment by TheWanderingCoel** [comment]
>

> > igniter么，问问trojan-gfw吧。毕竟不是我写的
> 
> 谢谢回复，不是igniter，就是Trojan-Qt5。
> pc端ss可以允许局域网其他设备接入，比如switch，Trojan-Qt5现在可以么

可以啊，你把本地地址设置到lan ip就行了
