### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by TakcC** [TheWanderingCoel/Trojan-Qt5#111]
首页看到0.0.4版本是Build Error跟Build Failing，是否哪里出问题了呢？
Release里面也还没看到0.0.4版本。

**Comment by TheWanderingCoel** [comment]
还有些新feature没做完，做完后release

**Comment by TakcC** [comment]
> 还有些新feature没做完，做完后release

好的，明白。

**Comment by TheWanderingCoel** [comment]
已完成，请等待构建完成后尝试``v0.0.4``
