### ISSUE TITLE
Can I copy terminal command like Shadowsocks?

### ISSUE THREAD

**Issue by sleepEarlier** [TheWanderingCoel/Trojan-Qt5#115]
Or which port does it use? I can alos do `export http_proxy=http://127.0.0.1:port;` myself.

**Comment by TheWanderingCoel** [comment]
Currently, you have to export it by yourself. Port is in ``profile editor``(v0.0.3 Bug Fix and before). For ``v0.0.4 and later``, it's in ``Advance Settings``.

**Comment by TheWanderingCoel** [comment]
Supported in ``v0.0.4b``
