### ISSUE TITLE
反应几个0.0.4版的小问题

### ISSUE THREAD

**Issue by ogog45** [TheWanderingCoel/Trojan-Qt5#117]
1.按照延迟(ping值)排序时，能不能吧错误排到最后而不是排在低延迟服务器前面。
2.延迟(ping值)较高时呈现黄色数字几乎不可阅读，麻烦改下配色

**Comment by TheWanderingCoel** [comment]
好的。能否建议下高延迟时候的配色？

**Comment by dr1llc4t** [comment]
mac版本惨不忍睹。。。我一度以为我眼镜掉了，我又回退回 0.0.3bug fix了

**Comment by TheWanderingCoel** [comment]
？？？0.0.4怎么了吗。

**Comment by dr1llc4t** [comment]
> ？？？0.0.4怎么了吗。

等我开完会，我新开个issue吧

**Comment by TheWanderingCoel** [comment]
好的，麻烦了

**Comment by ogog45** [comment]
> 好的。能否建议下高延迟时候的配色？

要不橙色试试？

**Comment by TheWanderingCoel** [comment]
> 要不橙色试试？

好的，如果有喜欢的橙色，麻烦发一下那个颜色的RGBA

**Comment by ogog45** [comment]
> > 要不橙色试试？
> 
> 好的，如果有喜欢的橙色，麻烦发一下那个颜色的RGBA

不懂呀，麻烦大佬了。
还有就是，这个新版的托盘图标不管单击或者双击都不会弹出界面。

**Comment by xhrm** [comment]
托盘图标菜单，中文显示不完整，点击与双击托盘图标无法打开主页面，需要点击恢复显示主页面

**Comment by TheWanderingCoel** [comment]
对，必须点击恢复才行

**Comment by TheWanderingCoel** [comment]
> > 好的。能否建议下高延迟时候的配色？
> 
> 要不橙色试试？

搞定了
