### ISSUE TITLE
从0.0.3 Bug Fix升级到0.0.4之后失效

### ISSUE THREAD

**Issue by caiziruo** [TheWanderingCoel/Trojan-Qt5#119]
测试延迟正常，但无法连接外网。

**Comment by TheWanderingCoel** [comment]
日志能否发一下？

**Comment by caiziruo** [comment]
macOS 版本 10.12.6，日志就下面一行

[2020-02-29 20:17:47] [WARN] trojan service (client) started at ::1:52478

**Comment by TheWanderingCoel** [comment]
如果从旧版本升级上来的，请先导出服务器（不能是gui-config.json）然后删除``~/.config/trojan-qt5``这个文件夹。重新开启新版本。
