### ISSUE TITLE
可以支持国际化吗？

### ISSUE THREAD

**Issue by free798** [TheWanderingCoel/Trojan-Qt5#12]
我的一大部分用户都是国际用户，需要支持英文！谢谢～

**Comment by free798** [comment]
我看到下载的windows文件里面，有国际化文件，请问我该如何修改，客户端才能显示英文？谢谢

**Comment by TheWanderingCoel** [comment]
把系统语言设置成英语就好了，非本地化地区显示的都是英文

**Comment by free798** [comment]
我把win10 的系统语言改成了英文，并重启了电脑～ 客户端内还是显示的英文！ 好的，多谢解答，我再试试

**Comment by TheWanderingCoel** [comment]
> 我把win10 的系统语言改成了英文，并重启了电脑～ 客户端内还是显示的英文！ 好的，多谢解答，我再试试

不是说支持英文么...
