### ISSUE TITLE
Mac 升级 0.0.4 问题反馈

### ISSUE THREAD

**Issue by moqimoqidea** [TheWanderingCoel/Trojan-Qt5#120]
Mac 系统：10.15.3
目前问题：

* 单节点点击 socks5 + http，程序直接退出。

* 界面显示字都是糊了的😂
<img width="1680" alt="Snipaste_2020-02-29_19-38-58" src="https://user-images.githubusercontent.com/39821951/75606829-c8defe00-5b2b-11ea-9fe4-7006e802b08e.png">

**Comment by TheWanderingCoel** [comment]
哪里字糊了？能否发个图，第一个问题请发下日志

**Comment by moqimoqidea** [comment]
糊了就是感觉字体虚化了，可能有前端和 UI 经验的人描述的更清楚点，这个问题等他们反馈吧再。

第一个问题的日志：
[crash_detail.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4270252/crash_detail.txt)

**Comment by moqimoqidea** [comment]
只使用 socks 是可以连接的，但是点击 socks + http 就会 crash。 已经排除配置原因，配置是使用 URI新配的单节点，不是从 v0.0.3-bug-fix 平移过来的。

**Comment by StaZhu** [comment]
同样的问题 使用socks+http，秒崩溃，我是今天新下的，配置都是新导入的

**Comment by TheWanderingCoel** [comment]
请先使用socks吧，我看下什么问题

**Comment by TheWanderingCoel** [comment]
能否打开``~/.config/trojan-qt5`` 的``privoxy.conf``看一下，把配置发出来。

**Comment by StaZhu** [comment]
listen-address :0
toggle 0
show-on-task-bar 0
activity-animation 0
forward-socks5 / :0 .
hide-console

**Comment by TheWanderingCoel** [comment]
配置文件炸了，估计写的时候出了点问题。

**Comment by TheWanderingCoel** [comment]
看下高级设置的里的东西？能否麻烦截个图？

**Comment by MatthewDevelop** [comment]
![image](https://user-images.githubusercontent.com/23044942/75607677-938ade00-5b34-11ea-8c8c-55719085aad8.png)
我这边mac系统升级之后是这样的，完全用不了

**Comment by StaZhu** [comment]
高级设置什么都没动

**Comment by StaZhu** [comment]
我其实奇怪 全局模式 高级设置为啥不给默认填好127.0.0.1 和8070端口号 还得自己填？

**Comment by TheWanderingCoel** [comment]
> 我其实奇怪 全局模式 高级设置为啥不给默认填好127.0.0.1 和8070端口号 还得自己填？

不是，主要是之前有过旧版本的因为旧配置文件没有这东西，所有全都会变成空的。
直接把那个配置文件夹``~/.config/trojan-qt5``删了就好

**Comment by TheWanderingCoel** [comment]
> ![image](https://user-images.githubusercontent.com/23044942/75607677-938ade00-5b34-11ea-8c8c-55719085aad8.png)
> 我这边mac系统升级之后是这样的，完全用不了

点不了么？

**Comment by MatthewDevelop** [comment]
界面上显示已连接，但是不会设置系统代理，配合switcy-omega也不能用，就像服务没运行起来，而且这个UI很废眼睛

**Comment by StaZhu** [comment]
感觉可以不考虑兼容性，全局模式默认填一下127.0.0.1 和 8070 , 不然小白根本不知道哪个端口号，还得拿命令sudo lsof -iTCP -sTCP:LISTEN -nP 看端口号，新手根本不知道咋配置

**Comment by TheWanderingCoel** [comment]
> 感觉可以不考虑兼容性，全局模式默认填一下127.0.0.1 和 8070 , 不然小白根本不知道哪个端口号，还得拿命令sudo lsof -iTCP -sTCP:LISTEN -nP 看端口号，新手根本不知道咋配置

是默认的，只是从老版本升级上来不会自动填

**Comment by StaZhu** [comment]
不是默认的 我今天第一次装，装的就是0.0.4

**Comment by TheWanderingCoel** [comment]
真是奇了怪了...大家都别下0.0.4了我这里测试没问题的不知道为啥release一堆bug

**Comment by TheWanderingCoel** [comment]
有没有倒入过``gui-config.json``?导入的话可能会直接清除掉配置文件（如果不是0.0.4导出的话）

**Comment by TheWanderingCoel** [comment]
> 界面上显示已连接，但是不会设置系统代理，配合switcy-omega也不能用，就像服务没运行起来，而且这个UI很废眼睛

升级上来的话可能会破坏整个配置文件。能否把``~/.config/trojan-qt5``整个删掉？（请先备份好服务器信息）

**Comment by StaZhu** [comment]
我是今天第一次用 下好了导入gui-config.json 然后用不了 看下系统代理发现socks被带到1:1这个错误地址了 然后发现高级设置没有socks配置 自己加了下127.0.0.1:8070 软件才能正常用

**Comment by StaZhu** [comment]
然后socks 改socks+http 打开后百分百崩溃 删配置目录重新导入才能进软件

**Comment by TheWanderingCoel** [comment]
导入gui-config会导致高级配置错误，0.0.4a马上修复

**Comment by TheWanderingCoel** [comment]
> Mac 系统：10.15.3
> 目前问题：
> 
> * 单节点点击 socks5 + http，程序直接退出。
> * 界面显示字都是糊了的😂
> 
> <img alt="Snipaste_2020-02-29_19-38-58" width="1680" src="https://user-images.githubusercontent.com/39821951/75606829-c8defe00-5b2b-11ea-9fe4-7006e802b08e.png">

麻烦告诉哪个界面是糊的？

**Comment by moqimoqidea** [comment]
> > Mac 系统：10.15.3
> > 目前问题：
> > 
> > * 单节点点击 socks5 + http，程序直接退出。
> > * 界面显示字都是糊了的😂
> > 
> > <img alt="Snipaste_2020-02-29_19-38-58" width="1680" src="https://user-images.githubusercontent.com/39821951/75606829-c8defe00-5b2b-11ea-9fe4-7006e802b08e.png">
> 
> 麻烦告诉哪个界面是糊的？

总体而言在我电脑上屏幕，感觉 0.0.3 是黑体，而 0.0.4 都是灰色的，大概是这个感觉，每个界面都灰灰的。

**Comment by moqimoqidea** [comment]
目前 0.0.3 bug fix 的显示效果：

<img width="1000" alt="Snipaste_2020-02-29_22-44-07" src="https://user-images.githubusercontent.com/39821951/75609603-14ea6c80-5b45-11ea-9258-d59aa8f1aeaa.png">

**Comment by TheWanderingCoel** [comment]
状态用量什么的是灰色的吗？我设置的灰色啊，按照ui设计稿弄得

**Comment by moqimoqidea** [comment]
> 状态用量什么的是灰色的吗？我设置的灰色啊，按照ui设计稿弄得

了解的，那应该大部分是颜色差异导致的。

有一两个弹窗，就是程序申请每次打开自己检查更新那一两个，感觉有点像和分辨率适配没匹配上，字体发虚，有点像 Mac 接了外接显示器那种状态。

**Comment by TheWanderingCoel** [comment]
![](https://user-images.githubusercontent.com/39617891/75610183-cc817d80-5b49-11ea-8a44-9879f9abe20e.png)
其实不是很虚啊，检查更新的那个吗？是外部的框架，不是我的ui里的。
看上去也没啥问题啊。
![](https://user-images.githubusercontent.com/39617891/75610199-f2a71d80-5b49-11ea-86dd-dace0ef7abac.png)

**Comment by moqimoqidea** [comment]
在我这刚才打开看起来不是那样的，等下次触发了截图给你。 😅

**Comment by TheWanderingCoel** [comment]
好的麻烦了

**Comment by moqimoqidea** [comment]
我这不麻烦，就是贡献个测试用例，麻烦你了。🍻

**Comment by Saberwhy** [comment]
字体模糊
<img width="531" alt="WeChatd01d985f594863850b282668d98476d8" src="https://user-images.githubusercontent.com/20423638/75618261-98887580-5ba6-11ea-8f46-04e0a5d137aa.png">
MacOS版本: 10.15.1
Trojan-Qt5版本: 0.0.4a

**Comment by TheWanderingCoel** [comment]
编辑那个工具栏的还是下面那个服务器栏的？

**Comment by dr1llc4t** [comment]
不是字体模糊，是整个界面没有适配HDPI

**Comment by TheWanderingCoel** [comment]
ui苦手哎

**Comment by bbbear2002** [comment]
他的意思就是程序没有视网膜化

**Comment by TheWanderingCoel** [comment]
研究中...0.0.4b可能会修复

**Comment by dr1llc4t** [comment]
> 研究中...0.0.4b可能会修复

有人folk了一个 shadowsocksX-NG，然后就是把协议改成了 trojan，目前在用那个，操作习惯啥的都不用改。Owner可以看看那个，叫做TrojanX。Anyway，感谢owner，感谢所有的开发者，有开捐助的话，我会支持开发者的。

**Comment by TheWanderingCoel** [comment]
毕竟是跨平台的，照顾好所有平台太难了。Shadowsoxksx-NG很完善了，ss-qt已经不再更新了

**Comment by junpeng-li** [comment]
![1583339655389](https://user-images.githubusercontent.com/33470359/75901291-403cc680-5e79-11ea-8e99-e5b8c4098ac2.jpg),使用的socks,mac版本10.15.3，总是出现无法连接的问题，但是节点在win的另一台电脑上可以用。

**Comment by TheWanderingCoel** [comment]
日志

**Comment by moqimoqidea** [comment]
目前 v0.0.4b 解决了上述几个 bug，因此 issue 关闭。 

🍻🍻🍻
