### ISSUE TITLE
连接后提示Fatal error: invalid bind port spec :0

### ISSUE THREAD

**Issue by lmylmy9** [TheWanderingCoel/Trojan-Qt5#121]
这是什么意思啊。
一开始直接用json文件导入的，但是不能访问google等网站，回头看教程里说配置文件有问题，暂时别这么导入。然后我换成扫描屏幕二维码导入配置，连接的时候就提示这个错误，而且也不能访问网站。

**Comment by TheWanderingCoel** [comment]
直接删掉配置文件夹``~/.config/trojan-qt5``然后重新开启新版客户端

**Comment by lmylmy9** [comment]
我好像没有这个文件夹，不过我把本地服务器类型换成SOCKS5再连接就不会弹出上述错误。
但是我还是不能访问网站，这是什么原因。

**Comment by TheWanderingCoel** [comment]
什么系统,windows么？

**Comment by lmylmy9** [comment]
是的，windows8.1。
今天刚下载的Trojan-Qt5 0.0.4版本。

**Comment by TheWanderingCoel** [comment]
我换windows试一下，感谢反馈

**Comment by TheWanderingCoel** [comment]
把高级设置重新设置一下应该就好了

**Comment by lmylmy9** [comment]
试了下，还是不能访问网络。

**Comment by lmylmy9** [comment]
我是不是该用0.0.2。

**Comment by TheWanderingCoel** [comment]
能否发一下日志？

**Comment by lmylmy9** [comment]
[2020-02-29 21:31:18] [WARN] trojan service (client) started at 127.0.0.1:1080
[2020-02-29 21:31:30] [WARN] trojan service stopped
[2020-02-29 21:32:04] [WARN] trojan service (client) started at 127.0.0.1:1080
[2020-02-29 21:34:02] [WARN] trojan service stopped
[2020-02-29 21:35:07] [WARN] trojan service (client) started at 127.0.0.1:1080
[2020-02-29 21:37:26] [WARN] trojan service stopped
[2020-02-29 22:22:49] [WARN] trojan service (client) started at 127.0.0.1:1080

**Comment by lmylmy9** [comment]
不知道是什么原因。还是switchyOmega哪里设置错了，我以前用shadowsocks时不安装这种浏览器插件，今天看教程第一次用。

**Comment by lmylmy9** [comment]
我把switchyOmega切成代理模式就好了。
那为什么系统代理就不行呢。

**Comment by TheWanderingCoel** [comment]
系统代理没设置上么？

**Comment by lmylmy9** [comment]
这不太懂，系统代理是自己在控制面板中设置的？还是在TrojanQt5或者浏览器插件里设置的？

**Comment by TheWanderingCoel** [comment]
设置代理里的，请尝试0.0.4a。不选择http的话系统代理是不会被设置的，那个bug现在修好了

**Comment by lmylmy9** [comment]
我换成0.0.4a了，点系统代理还是不能访问。虽然现在不妨碍正常使用，但还是想搞明白哪出问题了
怎么看系统代理是否被设置呢，没被设置的原因一般有哪些呢。

**Comment by lmylmy9** [comment]
我好像乌龙了，是不是只要在软件内设置-常规设置里勾选自动设置系统代理和启用PAC模式，然后右下角选PAC Mode，浏览器选系统代理就既可以访问国内网站也可以访问国外网站了。
我当时怎么会没勾选呢，如果没问题的话我把这个问题关了。

**Comment by TheWanderingCoel** [comment]
浏览器必须要设置跟随系统代理的，004c问题会少很多
