### ISSUE TITLE
UI 延迟字体颜色建议调整

### ISSUE THREAD

**Issue by fyuan1316** [TheWanderingCoel/Trojan-Qt5#122]
版本：0.0.4
os ： macos high sierra 10.13.6

黄色的字体看起来不是很清晰？建议能调整下。

![image](https://user-images.githubusercontent.com/42265657/75607840-f466e600-5b35-11ea-90e4-cbf2b971b66d.png)

**Comment by TheWanderingCoel** [comment]
嗯，刚才也有人提了。会改成橘色

**Comment by TheWanderingCoel** [comment]
已完成
