### ISSUE TITLE
在0.0.4版本下，IDM又无法正常使用

### ISSUE THREAD

**Issue by EA-DICE** [TheWanderingCoel/Trojan-Qt5#124]
在0.03版本可以正常使用，但0.0.4版本下，IDM无速度并且报错，IDM设置未作任何更改

**Comment by TheWanderingCoel** [comment]
0.0.4bug太多了，系统设置什么的全混乱了。我尽量赶快修复

**Comment by EA-DICE** [comment]
辛苦作者了

**Comment by TheWanderingCoel** [comment]
没事，请给我点时间。我稍后修复

**Comment by EA-DICE** [comment]
我暂时退回0.0.3版本

**Comment by TheWanderingCoel** [comment]
删掉配置文件config.ini,尝试v0.0.4a

**Comment by EA-DICE** [comment]
抱歉，昨天先休息了。连夜修复bug的作者是好作者！

**Comment by EA-DICE** [comment]
但在更新至0.0.4版本后，IDM仍然无法正常下载需要代理的文件

**Comment by TheWanderingCoel** [comment]
004a么？

**Comment by EA-DICE** [comment]
是的，是0.0.4a

**Comment by TheWanderingCoel** [comment]
检查下高级设置？

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/75617940-f2863c80-5ba0-11ea-982a-9146c0998742.png)
我把上个版本根文件夹全部删除然后下载了最新版本，配置文件重新导入，设置如下
![image](https://user-images.githubusercontent.com/42771283/75617948-23ff0800-5ba1-11ea-9258-68fcbc3e8d3f.png)

**Comment by EA-DICE** [comment]
我的网络服务提供商不建议我打开“自动设置系统代理”这一选项，而我在chrome浏览器中使用switchyomega这一代理并搭配gfwlist使用

**Comment by TheWanderingCoel** [comment]
idm报啥错误？

**Comment by EA-DICE** [comment]
我不知道Trojan客户端的pac模式是否需要启用

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/75617978-d8009300-5ba1-11ea-93e3-864893d4dede.png)
一直无速度

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/75617982-fc5c6f80-5ba1-11ea-8940-5b116ea1616a.png)
IDM代理设置如下

**Comment by TheWanderingCoel** [comment]
不要填密码。。。

**Comment by TheWanderingCoel** [comment]
无论是socks5还是http都不需要密码，trojan和privoxy开放的本地端口均没有密码和用户名验证

**Comment by EA-DICE** [comment]
去除密码后问题仍存在
![image](https://user-images.githubusercontent.com/42771283/75618054-5c074a80-5ba3-11ea-8895-51b744d52851.png)

**Comment by EA-DICE** [comment]
去除密码后问题仍然存在
![image](https://user-images.githubusercontent.com/42771283/75618066-7ccfa000-5ba3-11ea-89dc-c26ad504660c.png)

**Comment by TheWanderingCoel** [comment]
试试浏览器打不打得开？

**Comment by EA-DICE** [comment]
浏览器没有任何问题，可以正常访问

**Comment by TheWanderingCoel** [comment]
试试只设置socks5？

**Comment by EA-DICE** [comment]
是指在Trojan客户端中设置吗

**Comment by EA-DICE** [comment]
设置已经是socks5了

**Comment by TheWanderingCoel** [comment]
关掉使用http https 设置开启socks5 地址127.0.0.1 端口1080

**Comment by EA-DICE** [comment]
trojan客户端中本地服务器类型设置为仅socks5，idm设置如下图
![image](https://user-images.githubusercontent.com/42771283/75618361-f9647d80-5ba7-11ea-94c9-540f68f9e922.png)idm仍然无速度

**Comment by TheWanderingCoel** [comment]
试试用idm下别的呢？麻烦把trojan日志贴一下

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/75618440-78a68100-5ba9-11ea-8964-0ecd16bc8bd0.png)
在下载不需要代理的文件时也显示无速度，trojan日志
[trojan.log](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4271259/trojan.log)

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/75618961-3cc2ea00-5bb0-11ea-8463-a35e710b0301.png)
IDM报错界面

**Comment by TheWanderingCoel** [comment]
看样子是服务器问题？
```
0 bytes received, 583 bytes sent, lasted for 0 seconds
[2020-03-01 10:20:46] [INFO] 127.0.0.1:2057 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-03-01 10:20:46] [INFO] 127.0.0.1:2059 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-03-01 10:20:46] [INFO] 127.0.0.1:2060 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
cannot establish connection to remote server xxxx.xyz:443: ÓÉÓÚÏß³ÌÍË³ö»òÓ¦ÓÃ³ÌÐòÇëÇó£¬ÒÑÖÐÖ¹ I/O ²Ù×÷¡£

**Comment by EA-DICE** [comment]
我稍后进行测试

**Comment by TheWanderingCoel** [comment]
由于线程退出或应用程序请求，已中止 I/O 操作。我decode了一下这个错误

**Comment by EA-DICE** [comment]
我找到一种可行的方法，在trojan客户端中将本地服务器类型设置为socks5+http，再在idm的代理设置中勾选http和https，我猜测一开始的问题应该是作者在0.0.4版本更改了导入时的策略，默认仅使用socks而不是socks+http，导致idm设置与trojan设置不对口

**Comment by TheWanderingCoel** [comment]
所有服务器的设置都会跟随gui-config.json的设置，请不要使用不同版本导出的进行导入

**Comment by EA-DICE** [comment]
我使用的是isp给的config，从没有更改过config的内容，也没有跨版本导入或导出

**Comment by TheWanderingCoel** [comment]
我gui-config.json经常变得，服务提供商给的不一定是当前版本的

**Comment by EA-DICE** [comment]
意思是有可能给的config和最新版本不兼容？

**Comment by TheWanderingCoel** [comment]
嗯

**Comment by TheWanderingCoel** [comment]
就比如会导致高级设置全都是空的啥的

**Comment by EA-DICE** [comment]
好的，多谢提醒，以后会多加留意的，但能否解答下http和socks5之间的区别？不太懂

**Comment by TheWanderingCoel** [comment]
socks5是一个协议,http也是一个协议。windows不支持socks5作为代理，所以需要开启http

**Comment by EA-DICE** [comment]
好的，明白了，给你添了这么多麻烦，不好意思

**Comment by TheWanderingCoel** [comment]
没事。

**Comment by railgunpoi** [comment]
> 我找到一种可行的方法，在trojan客户端中将本地服务器类型设置为socks5+http，再在idm的代理设置中勾选http和https，我猜测一开始的问题应该是作者在0.0.4版本更改了导入时的策略，默认仅使用socks而不是socks+http，导致idm设置与trojan设置不对口，在将本地服务器类型设置为socks5+http后，idm也对应设置后，需要代理的文件可以正常下载了

我今天在用了这个办法后试了一下能下油管视频了,但过了一会儿又下不了了,怎么调都不行

**Comment by EA-DICE** [comment]
换下服务器试试ii

**Comment by railgunpoi** [comment]
> 换下服务器试试

试了很多个都不行,下载不需要代理的文件是可以的

**Comment by EA-DICE** [comment]
等下帮你看看

**Comment by railgunpoi** [comment]
> 等下帮你看看

![image](https://user-images.githubusercontent.com/48752116/75872948-0902f100-5e4a-11ea-9db9-cc6ee123d291.png)
![image](https://user-images.githubusercontent.com/48752116/75872980-17510d00-5e4a-11ea-8f32-5494fdea6a90.png)
![image](https://user-images.githubusercontent.com/48752116/75872996-1ae49400-5e4a-11ea-82f6-8b05e5db6271.png)

设置是这样的

**Comment by EA-DICE** [comment]
IDMhttp和https端口设置为1081，socks5不勾选

**Comment by railgunpoi** [comment]
> IDMhttp和https端口设置为1081，socks5不勾选

能下了，感谢！！！

**Comment by EA-DICE** [comment]
下次记得选对端口

**Comment by railgunpoi** [comment]
> 下次记得选对端口

就跟你说的时候能下了,现在又不行了....

**Comment by EA-DICE** [comment]
等下帮你看看

**Comment by railgunpoi** [comment]
> 等下帮你看看
![image](https://user-images.githubusercontent.com/48752116/75883830-a23c0280-5e5e-11ea-99c1-56772b32aa6b.png)

**Comment by railgunpoi** [comment]
> 等下帮你看看

![image](https://user-images.githubusercontent.com/48752116/75883934-d0b9dd80-5e5e-11ea-93c8-3ff2bca052c4.png)

**Comment by EA-DICE** [comment]
看本地服务器类型有没有开启socks5+http

**Comment by railgunpoi** [comment]
> 看本地服务器类型有没有开启socks5+http

开了的

**Comment by EA-DICE** [comment]
还有就是，这都多久之前的视频了，ui都没更新，建议看mj最新视频教你玩inna

**Comment by EA-DICE** [comment]
服务器打码

**Comment by EA-DICE** [comment]
延迟全部测速，按延迟从低到高排序，选个延迟低一点的

**Comment by railgunpoi** [comment]
> 延迟全部测速，按延迟从低到高排序，选个延迟低一点的

换了个延迟最低的hk,还是不行,感觉好玄学,之前下午的时候按你说的调成1081就能下了,但过一会儿又不行了

**Comment by EA-DICE** [comment]
彩虹六号这一块还得看我盆骨的

**Comment by EA-DICE** [comment]
访问YouTube有问题吗

**Comment by railgunpoi** [comment]
> 访问YouTube有问题吗

没有,只有idm不行

**Comment by EA-DICE** [comment]
好的，等下测试看看

**Comment by railgunpoi** [comment]
> 好的，等下测试看看

不知道是哪边的问题,我今天下午测试的时候还留着一个油管视频没下完,现在可以继续下载有速度,但是去下新的就不行咯

**Comment by railgunpoi** [comment]
> 好的，等下测试看看

解决了,是我太急了...下载点的太快,要等他几秒解析出真正的链接出来,当然也可能只是现在好了,并不是这原因,明天再看看

**Comment by EA-DICE** [comment]
我倒没考虑过这个问题

**Comment by EA-DICE** [comment]
我不认为是这个问题，下次出现问题了再具体分析吧
