### ISSUE TITLE
请使用0.0.4a Please use 0.0.4a

### ISSUE THREAD

**Issue by TheWanderingCoel** [TheWanderingCoel/Trojan-Qt5#125]
这个版本都是bug,实在很对不起大家。请使用之后的0.0.4a

**Comment by avalond** [comment]
每次发一次新版本，就添加一个版本号，无论是修bug 还是添加新功能，都不会产生麻烦

**Comment by TheWanderingCoel** [comment]
如果一个新版本发出来后，如果有特别严重的bug我一般会后面添加一个字母之类的，不会当作下一个正式版

**Comment by Itzamana** [comment]
> 这个版本都是bug,实在很对不起大家。请使用之后的0.0.4a

能更新维护就很感激了，感谢！
顺便希望节点列表的排序可以增加“按添加时间”排序，或者可以手动排序也行…

**Comment by persevereVon** [comment]
我竟然能正常使用，我是 windows 操作系统。感谢作者对自由的贡献❤

**Comment by coderstory** [comment]
免费提供给大家的也不好有什么要求 
建议弄个 test group吧
开个tg群什么的
一个人再怎么测试也会遗漏
跟何况是跨平台啊

**Comment by TheWanderingCoel** [comment]
可以，开个tg群。

**Comment by TheWanderingCoel** [comment]
对tg有点后怕，慢慢来吧。接下来越来越忙可能就不维护了

**Comment by persevereVon** [comment]
我草，兄弟，tg 不安全吗，我他妈上面言论太不好，害怕

**Comment by TheWanderingCoel** [comment]
翻了出去言论也还需理智啊，安不安全不做评价。不清楚事实

**Comment by TheWanderingCoel** [comment]
搜TrojanQt5进群了各位

**Comment by mouseroser** [comment]
可以使用电报建个群

**Comment by TheWanderingCoel** [comment]
https://t.me/Trojan-Qt5
