### ISSUE TITLE
【macOS 外观问题等】Trojan-Qt5 v. 0.0.4a 版本字体、图标模糊...

### ISSUE THREAD

**Issue by DonghanLyu** [TheWanderingCoel/Trojan-Qt5#129]
问题1: macOS Catalina 10.15.3 系统，MacBook Air 视网膜显示屏带有 Touch ID 及 T2 安全芯片机型。已经在“系统偏好设置”中关闭“使用平滑字体（可用时）”选项。新版的 Trojan 在当前环境下外观模糊，图标、字体均出现了此问题。
<img width="550" alt="截屏2020-03-01上午8 56 50" src="https://user-images.githubusercontent.com/41569712/75617601-45112a00-5b9c-11ea-8622-2479c07faa56.png">
![IMG_0336](https://user-images.githubusercontent.com/41569712/75617604-4a6e7480-5b9c-11ea-92b6-fd5b9af26bab.JPG)

问题2: 看到处于状态栏的 Trojan 图标的弹出窗口，猜想您应该是想将快速启动/关闭功能添加进来，但是目前在前文所述机型上无法快速启动/关闭 Trojan 服务。

问题3: 目前仍无法点按位于 Dock 栏上的 Trojan 图标快速唤出 Trojan 主屏幕。

优化1: 目前已连接条目可否修改配色，淡蓝色背景色加上黑色粗体可能无法看清。

感谢开发者的贡献，谢谢。

**Comment by TheWanderingCoel** [comment]
2的话其实关闭很好做，开启如何判断是哪个服务器被选中需要点时间。
3的话我并没有加dock图标唤出，直接在状态栏隐藏dock图标直接被隐藏。
1）淡蓝色加的是灰色（加粗）能看清的，我按着设计稿的颜色弄得

**Comment by DonghanLyu** [comment]
回-2 如果在初次唤出 Trojan 且没有选定的话，可以直接将主窗口唤出，并弹出或通知选择想使用服务器。
回-3 我习惯将常用软件放在 Dock 栏，可能没有跟您的使用需求重叠，我之后将其移出，谢谢。
回-1） 好的。

问题1: 请问字体、图标模糊问题是可以在下个版本修复吗？

感谢开发者。

**Comment by ShineUnM** [comment]
搭车反馈一下macOS 10.15.x下的情况
1. proxy功能已经正常
2. 似乎没有适配drak mode
3. trojan-qt5.app似乎有附加属性没有清除(或者需要apple认可的签名？），需要xattr -c -r清除，否则系统报错无法打开程序

**Comment by TheWanderingCoel** [comment]
我想起来了,那个sparkle自动更新框架一定要签名...我有开发者证书但是我不敢签名。dark mode没有设计稿，我直接锁定成白色的主题了。

**Comment by TheWanderingCoel** [comment]
> 回-2 如果在初次唤出 Trojan 且没有选定的话，可以直接将主窗口唤出，并弹出或通知选择想使用服务器。
> 回-3 我习惯将常用软件放在 Dock 栏，可能没有跟您的使用需求重叠，我之后将其移出，谢谢。
> 回-1） 好的。
> 
> 问题1: 请问字体、图标模糊问题是可以在下个版本修复吗？
> 
> 感谢开发者。

这个主要是我找不到原因，在我这台macbook Air (2017)上看不出来

**Comment by ShineUnM** [comment]
> 我想起来了,那个sparkle自动更新框架一定要签名...我有开发者证书但是我不敢签名。dark mode没有设计稿，我直接锁定成白色的主题了。

sparkle.framework签名是担心GA叔叔还是copyright问题？ 我记得TNT xx的app都会重签一遍的，否则也会报错，需要xattr

dark mode下主要是菜单和工具栏图标下的文字看不清楚，我强制改成系统风格菜单，只显示图标，也能用, 反正正常情况下都是最小化, :)

文字模糊是不是qt5 api里面适配视网膜的api没有设置生效？ 

ps, Thanks for your great job again.

**Comment by TheWanderingCoel** [comment]
1）签名上有自己的真名，被查水表就很无奈了。没签名
2）想了想还是锁白色主题了，改天看看大佬能不能设计个黑色界面的hhh
3）这api我也不知道怎么搞，研究下

**Comment by sidoinefr** [comment]
折腾了一下，目前可以正常使用了，开发者辛苦了，效率还是很高的，mac下也有了中文，测试延迟部分，白色背景，黄色字体我本人是看不清数值，不知道下个版本能否改成红色系，或者别的颜色。其他设计方面的东西，比如上面大家写的字体模糊之类的，倒是不影响使用，更多是美观方面的改进，考虑到开发者的繁重工作，我觉得已经先解决有没有的问题，再解决好不好的问题，我代表一部分用户，感谢开发者的辛苦工作！希望软件越来越棒，功能越来越全，界面越来越美观！致敬！

**Comment by TheWanderingCoel** [comment]
> 折腾了一下，目前可以正常使用了，开发者辛苦了，效率还是很高的，mac下也有了中文，测试延迟部分，白色背景，黄色字体我本人是看不清数值，不知道下个版本能否改成红色系，或者别的颜色。其他设计方面的东西，比如上面大家写的字体模糊之类的，倒是不影响使用，更多是美观方面的改进，考虑到开发者的繁重工作，我觉得已经先解决有没有的问题，再解决好不好的问题，我代表一部分用户，感谢开发者的辛苦工作！希望软件越来越棒，功能越来越全，界面越来越美观！致敬！

感谢您的支持~0.0.4a已经把黄色改成橘色了，应该会好一点。我最近几天可能会更新慢一点，抱歉

**Comment by DonghanLyu** [comment]
> > 折腾了一下，目前可以正常使用了，开发者辛苦了，效率还是很高的，mac下也有了中文，测试延迟部分，白色背景，黄色字体我本人是看不清数值，不知道下个版本能否改成红色系，或者别的颜色。其他设计方面的东西，比如上面大家写的字体模糊之类的，倒是不影响使用，更多是美观方面的改进，考虑到开发者的繁重工作，我觉得已经先解决有没有的问题，再解决好不好的问题，我代表一部分用户，感谢开发者的辛苦工作！希望软件越来越棒，功能越来越全，界面越来越美观！致敬！
> 
> 感谢您的支持~�0.0.4a已经把黄色改成橘色了，应该会好一点。我最近几天可能会更新慢一点，抱歉

非常感谢开发者，但目前我还是发现 Trojan 启动后会启用 Dock 栏，而且无法点击 Dock 图标唤出主屏幕。如果可能，请完善从 Dock 栏唤出主屏幕的功能，非常感谢。

**Comment by TheWanderingCoel** [comment]
这个我研究下，0.0.4b里尽量加入

**Comment by DonghanLyu** [comment]
> 这个我研究下，0.0.4b里尽量加入

感谢回复，祝万事遂意。

**Comment by TheWanderingCoel** [comment]
感谢
