### ISSUE TITLE
请问怎么设置局域网共享代理？

### ISSUE THREAD

**Issue by xerohuang** [TheWanderingCoel/Trojan-Qt5#134]
尝试设置了本地地址为0.0.0.0或者局域网ip都不行

**Comment by TheWanderingCoel** [comment]
![QQ20200301-145004](https://user-images.githubusercontent.com/39617891/75621133-f67b8400-5bcb-11ea-89f0-5ff248d0b03c.png)
都设置成局域网Ip应该就可以了

**Comment by qinqinwodetao** [comment]
我也遇到同样问题,虚拟机telnet ip port是不通的!

**Comment by TheWanderingCoel** [comment]
虚拟机？？？怕有病毒么。你选的啥网络类型

**Comment by qinqinwodetao** [comment]
@TheWanderingCoel 
![image](https://user-images.githubusercontent.com/5457093/75642644-2b90e080-5c77-11ea-89ed-2a5639351900.png)
![image](https://user-images.githubusercontent.com/5457093/75642819-d7d2c700-5c77-11ea-9db8-f860d8930e0e.png)
![image](https://user-images.githubusercontent.com/5457093/75642654-321f5800-5c77-11ea-85ca-a0f670616596.png)

trojan 程序部署在win主机上面,不是怕病毒哈,  win主机其他程序通过自身的1081端口能够使用代理,但是nat网络下的虚拟机内部无法联通,麻烦帮忙确认下!

**Comment by TheWanderingCoel** [comment]
设置下地址为192.168.1.1?socks5和http的

**Comment by qinqinwodetao** [comment]
设置下地址为192.168.1.1 可以了,还有配置内部默认只开启socke5 这个之前没注意到,感谢,现在可以用了! @TheWanderingCoel

**Comment by TheWanderingCoel** [comment]
好的，没事哈。👌

**Comment by xerohuang** [comment]
Socks5代理地址设置成0.0.0.0是可以用的，
但是Http代理地址必须设置成局域网IP才可以，0.0.0.0用不了

**Comment by TheWanderingCoel** [comment]
可能跟privoxy有关系

**Comment by TheWanderingCoel** [comment]
close as solved now
