### ISSUE TITLE
链接导入 建议直接捕获剪贴板  而不是手动输入

### ISSUE THREAD

**Issue by akirayoo** [TheWanderingCoel/Trojan-Qt5#137]
这样的话操作会方便很多  如果可能的话能支持批量导入就更好了

**Comment by TheWanderingCoel** [comment]
批量导入是支持的哈，直接捕获剪贴板像shadowrocket那样么？可以添加

**Comment by akirayoo** [comment]
> 批量导入是支持的哈，直接捕获剪贴板像shadowrocket那样么？可以添加

对的  ,另外我指的批量是剪贴板内有多个链接 然后一次性导入

**Comment by TheWanderingCoel** [comment]
好的👌

**Comment by TheWanderingCoel** [comment]
close as finished now
