### ISSUE TITLE
MAC端使用以太网端，无法自动设置系统代理

### ISSUE THREAD

**Issue by MatthewDevelop** [TheWanderingCoel/Trojan-Qt5#14]
mac连接以太网端时候，打开客户端并连接服务器，不会自动设置为系统代理

**Comment by TheWanderingCoel** [comment]
``v0.0.2``只对Wi-Fi进行设置，已经修复，``v0.0.3``将不会出现此问题。

**Comment by TheWanderingCoel** [comment]
https://github.com/TheWanderingCoel/Trojan-Qt5/commit/a90400384be58af96b26f68d94c60a51e20befa1
