### ISSUE TITLE
新UI很漂亮，申请修改黄色配色，白底实在看不清楚

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#142]
![Snipaste_2020-03-02_13-42-28](https://user-images.githubusercontent.com/31977161/75648712-db704900-5c8b-11ea-939d-339df0afe271.png)
不知道是不是我显示器的问题，黄色的字完全看不清楚，其他颜色ok。再次感谢老大！

**Comment by TheWanderingCoel** [comment]
004a试试？

**Comment by babylife** [comment]
本地可以修改吗？我2个显示器，DELL的还可以接受，acer的真的是看不清，倒是不知道怎么调配显示器哈哈

**Comment by TheWanderingCoel** [comment]
004a啊改成橘色了啊。试试004a吧而不是004。github排序问题004在上面

**Comment by TheWanderingCoel** [comment]
https://github.com/TheWanderingCoel/Trojan-Qt5/releases/tag/v0.0.4a

**Comment by babylife** [comment]
哦哦哦好的好的，马上试试

**Comment by babylife** [comment]
完美解决，谢谢老大，可以close

**Comment by TheWanderingCoel** [comment]
好的，收到👌
