### ISSUE TITLE
功能需求： 双击任务栏最小化图标时候，可以弹出主UI

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#143]
目前似乎没有双击事件，必须要右键点恢复才可以调出来？

**Comment by TheWanderingCoel** [comment]
嗯，双击004b应该可以做出来

**Comment by babylife** [comment]
威武！

**Comment by TheWanderingCoel** [comment]
已完成。请使用``v0.0.4b``

**Comment by GuanHenan** [comment]
Mac 0.0.5 新需求
双击菜单栏图标打开窗口，这样就不用单击再点恢复了（我看之前的issue说0.0.4b实现该需求了？）；
窗口内双击节点直接连接节点，现在双击节点和右键是一个功能。

**Comment by DavidChou92** [comment]
> Mac 0.0.5 新需求
> 双击菜单栏图标打开窗口，这样就不用单击再点恢复了（我看之前的issue说0.0.4b实现该需求了？）；
> 窗口内双击节点直接连接节点，现在双击节点和右键是一个功能。

赞成任务栏双击打开窗口，右键点击恢复感觉不太方便
