### ISSUE TITLE
全局模式不起作用(V0.0.4a)

### ISSUE THREAD

**Issue by hsq0596** [TheWanderingCoel/Trojan-Qt5#146]
Trojan-QT5自带的PAC规则是在线更新的，不能手动修改（修改之后就自动重置了），而选择Global Mode，并没有实现所有网站都走代理路线的效果，有些网站还是连不上。请问要如何解决？

**Comment by TheWanderingCoel** [comment]
那些网站？需要研究下

**Comment by hsq0596** [comment]
> 那些网站？需要研究下

比如http://subhd.com/
我的意思是能否实现所有链接都走代理的全局模式？现在的Global Mode似乎是没有这个效果。

**Comment by TheWanderingCoel** [comment]
global mode应该会啊。可能是个bug，我研究下

**Comment by Sincky** [comment]
全局的确有问题，我选了全局模式，我的ip还是本地的，还有流量累计不会跑

**Comment by TheWanderingCoel** [comment]
bug，下个版本修复。流量统计没实现

**Comment by EmrysQ** [comment]
同样的 我的AO3也是连不上https://archiveofourown.org/ 感谢大佬

**Comment by TheWanderingCoel** [comment]
已完成。请等待几分钟后使用``v0.0.4b``
