### ISSUE TITLE
Always error when Connect

### ISSUE THREAD

**Issue by evildecay** [TheWanderingCoel/Trojan-Qt5#15]
Fatal error: cant't check configuration file
'Files/Trojan-Qt5/privoxy/privoxy.conf': (error: number 0)
![微信截图_20200221164250](https://user-images.githubusercontent.com/6789367/75018448-e1b33800-54c9-11ea-9364-88b2a31734de.png)

**Comment by yixun666** [comment]
same question as yours

**Comment by TheWanderingCoel** [comment]
Your Path can not include any space.

**Comment by evildecay** [comment]
@TheWanderingCoel Thank you!

**Comment by TheWanderingCoel** [comment]
> @TheWanderingCoel Thank you!

You're welcome. I will find a time and release the patch to fix this bug.

**Comment by yixun666** [comment]
居然没想到，hhhh

**Comment by TheWanderingCoel** [comment]
因为之前也有人问过hhh,一直以为是privoxy的问题就没修

**Comment by TheWanderingCoel** [comment]
The latest commit have fixed this issue, please wait for ``v0.0.3``.
