### ISSUE TITLE
希望Mac版能在程序坞中隐藏trojan-Qt5的图标

### ISSUE THREAD

**Issue by GuanHenan** [TheWanderingCoel/Trojan-Qt5#150]
v0.0.4a加入了最小化功能，但是程序坞的图标还在。可以只保留菜单栏的图标，将程序坞中的图标隐藏吗？像shadowsockX-NG那样。谢谢！

**Comment by qyzxg** [comment]
附议，谢谢，程序坞中隐藏图标，双击任务栏图标显示主程序

**Comment by qyzxg** [comment]
还有 0.04a Macos 10.14.5 本期用量和累计用量始终是0，已经在youtube上看了几个小时视频了

**Comment by TheWanderingCoel** [comment]
图标隐藏会加入。流量记录还没实现

**Comment by qyzxg** [comment]
OK 流量记录没关系的 慢慢弄就行了，谢谢

**Comment by aobatu** [comment]
图标隐藏这个功能还是很需要的，期待能早日上线

**Comment by TheWanderingCoel** [comment]
点击最小化可以隐藏，但是恢复会把图标弄回来

**Comment by GuanHenan** [comment]
我更新到了0.0.4c，但是仍然无法隐藏dock中的应用图标，即使点击了最小化。

**Comment by maxsky** [comment]
建议设置为关闭窗口自动隐藏 dock 图标 ;)

**Comment by GuanHenan** [comment]
请问怎么设置？Mac的系统偏好设置和Trojan里没有找到这个设置，“关闭窗口自动隐藏dock图标”。
隐藏dock我可以设置，但是用command + tab切换应用程序时一直有Trojan，比较烦人。要是能像Alfred那样，运行但不显示图标就好了。


| |
关赫男
|
|
guan_henan@126.com
|
签名由网易邮箱大师定制


在2020年03月16日 01:03，Max Sky<notifications@github.com> 写道：

建议设置为关闭窗口自动隐藏 dock 图标 ;)

**Comment by maxsky** [comment]
😖描述错误，这是建议给开发者的，和 macOS 无关

**Comment by TheWanderingCoel** [comment]
目前想法是提供设置隐藏。

**Comment by TheWanderingCoel** [comment]
v0.0.4d已完成

**Comment by littlefisher666** [comment]
@TheWanderingCoel 求问，现在在程序坞中，怎么隐藏图标呢？我已经升级到1.2.0了的，在设置中没有发现哪个是隐藏图标的

**Comment by TheWanderingCoel** [comment]
![image](https://user-images.githubusercontent.com/39617891/85378448-25e44100-b56d-11ea-872f-fbd30f5431ec.png)

**Comment by littlefisher666** [comment]
3Q，之前看到了这个配置，但是勾选后点击OK发现没效果，我还以为这个功能没有呢。原来还需要重启一下才行的。sorry，问了个弱智问题
