### ISSUE TITLE
0.0.4a 外接USB網卡無法連接網絡

### ISSUE THREAD

**Issue by JimmyJimmyChan** [TheWanderingCoel/Trojan-Qt5#153]
版本：0.0.4a
系統：10.12.6 & 10.14.6

問題描述：使用USB網卡上網，程式設置「自動設置系統代理」已勾上情況下系統仍無法自動代理，手動設置可生效，但Telegram無法連接，即使手動設置127.0.0.1 1080也一樣連接不上。

麻煩作者看看是什麼問題，多謝！

![image](https://user-images.githubusercontent.com/47204324/75705677-cf6da100-5cf6-11ea-9a79-cc315a42c195.png)
![image](https://user-images.githubusercontent.com/47204324/75705688-d72d4580-5cf6-11ea-8547-569facd9eabd.png)

**Comment by TheWanderingCoel** [comment]
收到，004b修复

**Comment by JimmyJimmyChan** [comment]
好的，非常感謝！

**Comment by JavenZ** [comment]
我外接的usb网卡，手动勾选了SOCKS代理服务器，127.0.0.1 1080，可以使用。希望作者能处理成自动化的处理方式，感谢。

**Comment by JimmyJimmyChan** [comment]
@JavenZ 該問題已解決，多謝！

**Comment by TheWanderingCoel** [comment]
已完成。请等待几分钟后使用``v0.0.4b``
