### ISSUE TITLE
建议延迟排序的时候 把错误和超时的放在最后面

### ISSUE THREAD

**Issue by qyzxg** [TheWanderingCoel/Trojan-Qt5#156]
![image](https://user-images.githubusercontent.com/23406731/75738942-90633e00-5d3e-11ea-854e-03610321e6ef.png)

**Comment by TheWanderingCoel** [comment]
好的有时间可以修改一下

**Comment by qyzxg** [comment]
谢谢

**Comment by TheWanderingCoel** [comment]
v0.0.4d已完成
