### ISSUE TITLE
IOS有没有免费连接的软件啊

### ISSUE THREAD

**Issue by github-yitao** [TheWanderingCoel/Trojan-Qt5#159]
RT

**Comment by TheWanderingCoel** [comment]
没有

**Comment by bbbear2002** [comment]
shadowrocket 可以，只是速度比较慢

**Comment by qyzxg** [comment]
shadowrocket 不是免费的 2.99刀

**Comment by github-yitao** [comment]
> shadowrocket可以，只是速度比较慢

这个要2.99美元

**Comment by TheWanderingCoel** [comment]
可以研究下写个ios的，目前没时间

**Comment by github-yitao** [comment]
> 可以研究下写个ios的，目前没时间

shadowsocks git上有打包的，但是不敢用。。没放在appstore

**Comment by github-yitao** [comment]
> 可以研究下写个ios的，目前没时间

potatso lite能用不？

**Comment by TheWanderingCoel** [comment]
potatso lite不支持trojan，目前只有pharso pro和 shadowrocket支持，都要付费
