### ISSUE TITLE
v0.0.4a 全局模式不起作用的个例参考（Windows10）

### ISSUE THREAD

**Issue by LLLBlue** [TheWanderingCoel/Trojan-Qt5#162]
我是从gui-config.json批量导入的链接，使用全局模式没有起作用。
查看Windows设置-网络和Internet-代理，发现并没有开启使用代理设置。
手动开启代理地址127.0.0.1:8081，网络无法连接，于是怀疑HTTP代理没有生效。
**在软件中查看链接信息详情（编辑），发现本地服务器类型是SOCKS5。
修改为SOCKS5+HTTP，重新链接，OK。**

**Comment by LiZeCheng** [comment]
PAC模式能用吗？

**Comment by LLLBlue** [comment]
PAC可以用的

**Comment by LLLBlue** [comment]
或者我猜用SwitchyOmega之类的工具设置SOCKS5代理127.0.0.1:8080应该也没问题

**Comment by LLLBlue** [comment]
> PAC模式能用吗？

PAC可以用的

**Comment by TheWanderingCoel** [comment]
Windows下必须开启http才能设置代理，windows不支持socks5为系统代理，只支持socks4/4a

**Comment by LLLBlue** [comment]
> Windows下必须开启http才能设置代理，windows不支持socks5为系统代理，只支持socks4/4a

看到有类似问题，提供一个思路，而且我记得之前的版本导入之后直接就是SOCKS5+HTTP模式

**Comment by raylapse** [comment]
> > Windows下必须开启http才能设置代理，windows不支持socks5为系统代理，只支持socks4/4a
> 
> 看到有类似问题，提供一个思路，而且我记得之前的版本导入之后直接就是SOCKS5+HTTP模式

是的，前一版导入就是双模，最新004a导入只有socks5模式，需要自己改一下。

**Comment by TheWanderingCoel** [comment]
最新版直接从gui-config导入dualMode这个参数，没有这个参数默认socks5

**Comment by LLLBlue** [comment]
附：
v0.0.4a从gui-config.json批量导入链接时
批量将链接服务器类型设置为SOCKS5+HTTP模式的方法

![TIM截图20200306112911](https://user-images.githubusercontent.com/36073718/76047803-e1716d00-5f9e-11ea-81cc-707ca367e8e3.png)
打开gui-config.json，在configs里面的每一个object中添加一条属性"dual_mode": true

![TIM图片20200306112956](https://user-images.githubusercontent.com/36073718/76047829-ec2c0200-5f9e-11ea-80d3-21a2408a7e30.png)
可以找一行属性批量替换

从新导入链接，OK
