### ISSUE TITLE
User rule 能出个简单教程吗？

### ISSUE THREAD

**Issue by ShikGeng** [TheWanderingCoel/Trojan-Qt5#163]
比如我想把 *.beanfun.com 域名下的请求走代理，需要怎么配置
或者，想把 *.example.com 域名下设置白名单不走代理，又要怎么配置

**Comment by xhrm** [comment]
设置-用户规则-输入 *.beanfun.com 一行一个，保存重新连接

**Comment by ShikGeng** [comment]
试了一下。
http://hk.beanfun.com/Default.aspx   用chrome插件配的规则生效，能访问；换ie之后不能访问。

**Comment by ShikGeng** [comment]
> 设置-用户规则-输入 *.beanfun.com 一行一个，保存重新连接

试了一下。
http://hk.beanfun.com/Default.aspx 用chrome插件配的规则生效，能访问；换ie之后不能访问。

**Comment by ShikGeng** [comment]
上面规则好使，需要修改连接协议socks5+http
