### ISSUE TITLE
windows客户端打开trojan，配置节点后，无法连接

### ISSUE THREAD

**Issue by TobeManager** [TheWanderingCoel/Trojan-Qt5#17]
![0F0AU1Y _CAJ``RE9T32K2](https://user-images.githubusercontent.com/48972511/75019029-1ffd2700-54cb-11ea-96fb-2ca3b00b3235.png)
请问有人遇到这种情况吗？如何解决

**Comment by ZngZhu** [comment]
是的，我也遇到了，我这边一旦连接马上就闪退了

**Comment by TheWanderingCoel** [comment]
统一回复下，路径不能有空格，比如用户名之类的。的确是我这里没处理好

**Comment by Xxpain** [comment]
路径不能有中文和空格,  换了以后正常了, 谢谢您的项目 Orz

**Comment by TobeManager** [comment]
是的，刚才放到根目录下，配置节点后连接没有报错了。

**Comment by TheWanderingCoel** [comment]
> 路径不能有中文和空格, 换了以后正常了, 谢谢您的项目 Orz

没事，我尝试修复下这个Bug.

**Comment by TheWanderingCoel** [comment]
最新commit已修复，请等待``v0.0.3``
