### ISSUE TITLE
希望能增加白名单模式

### ISSUE THREAD

**Issue by ChuckRMB** [TheWanderingCoel/Trojan-Qt5#173]
现有的黑名单模式+用户规则虽然大体够用，但是对于经常访问国外网站的人来说需要大量自定义添加域名，比较麻烦。白名单模式就很好解决问题了，只有国内网站直连，其余网站一律走代理，很方便。

**Comment by TheWanderingCoel** [comment]
嗯，正在做了

**Comment by TheWanderingCoel** [comment]
根据Shadowsocks(RR)实现了，下个版本推送
![截屏2020-03-10下午5 38 57](https://user-images.githubusercontent.com/39617891/76299427-07c43f00-62f6-11ea-9ca1-1745e0be51c5.png)

**Comment by chandlerorange** [comment]
感谢开发，非常稳定

**Comment by TheWanderingCoel** [comment]
已完成。请等待几分钟后使用``v0.0.4b``
