### ISSUE TITLE
Is SNI encrypted when performing CONNECT？

### ISSUE THREAD

**Issue by creke** [TheWanderingCoel/Trojan-Qt5#178]
SNI encrypted is optional in TLS/1.3, I am wondering if Trojan-Qt5 makes an encrypted-SNI CONNECT or non-encrypted-SNI CONNECT.
Thank you :)

**Comment by TheWanderingCoel** [comment]
Hmmm. I think you may ask ``trojan-gfw`` for help about that? Haven't look at ``trojan`` source code yet. Sorry for that.

**Comment by creke** [comment]
> Hmmm. I think you may ask `trojan-gfw` for help about that? Haven't look at `trojan` source code yet. Sorry for that.

The original trojan-gfw does have an "sni" config that affects the CONNECT behaviour. It will be great if Trojan-Qt5 supports the "sni" config :)

```
sni: the Server Name Indication field in the SSL handshake. If left blank, it will be set to remote_addr.
```

**Comment by TheWanderingCoel** [comment]
Sure. Will consider about that. By default it's empty now.

**Comment by TheWanderingCoel** [comment]
Close as finished now
