### ISSUE TITLE
能不能像shadowsocks客户端一样，支持配置哪些节点使用代理，哪些直接走网路？

### ISSUE THREAD

**Issue by wuzhiming** [TheWanderingCoel/Trojan-Qt5#18]

**Comment by TheWanderingCoel** [comment]
不是很明白你的意思诶，能否详细的讲一下？

**Comment by wuzhiming** [comment]
shadowssocks 有几种模式，一个是全局模式，所有的请求走的shadowsocks配置的服务器，有个自动的模式，能把主流的需要翻墙的网站走代理服务器，剩下的直接走系统网络，不走代理，这样上国内的网站就比较快，
最后shadowsocks还有一个可以自定义规则的界面，让用户自己配置哪些网站走代理服务器如下图


![image](https://user-images.githubusercontent.com/6093737/75022540-34dcb900-54d1-11ea-8cb4-3d5f67909b95.png)

**Comment by TheWanderingCoel** [comment]
你说的是``PAC``的吧，这个重复了，release v0.0.3会支持。``user.rule``这个还需要研究下。

**Comment by wuzhiming** [comment]
嗯嗯，pac，这个比较实用，user.rule没有也暂时还好。老铁威武~

**Comment by soulcm** [comment]
顶，pac和user.rule望都支持下

**Comment by TheWanderingCoel** [comment]
> 顶，pac和user.rule望都支持下

``v0.0.3``已经支持``pac``了，``user.rule``正在研究。
