### ISSUE TITLE
如何在gui-config.json文件中设置本地服务器类型?

### ISSUE THREAD

**Issue by datarticle** [TheWanderingCoel/Trojan-Qt5#180]
默认的是SOCKS5，需要修改成SOCKS5 + HTTP。
由于节点较多，在UI界面中逐个设置起来很耗时。
请问如何在gui-config.json文件中统一修改？
谢谢！

**Comment by TheWanderingCoel** [comment]
每个{}里加一个"dual_mode": true,就行了。下一个版本直接把http模式变成全局了

**Comment by datarticle** [comment]
> 每个{}里加一个"dual_mode": true,就行了。下一个版本直接把http模式变成全局了

谢谢！

**Comment by neverno** [comment]
> > 每个{}里加一个"dual_mode": true,就行了。下一个版本直接把http模式变成全局了
> 
> 谢谢！

请问 gui-config.json 这很多节点的文件，怎么批量导进去 Trojan-Qt5 里用？我现在是一个一个手动添加，太累了...

**Comment by TheWanderingCoel** [comment]
文件->从gui-config.json导入连接就行了

**Comment by neverno** [comment]
> 文件->从gui-config.json导入连接就行了

感谢大大回复，可我目前用着Windows版 0.0.4a ，并没有从gui-config.json导入的选项，只有从config.json和从shadowrocket.json这2个选项

是要自己编译最新版么？

**Comment by TheWanderingCoel** [comment]
![QQ20200313-123745](https://user-images.githubusercontent.com/39617891/76590276-7d632180-6527-11ea-8ba0-56eba0806466.png)
不可能的啊，这个选项0.0.1就有了，你是不是从release下载的？

**Comment by neverno** [comment]
> ![QQ20200313-123745](https://user-images.githubusercontent.com/39617891/76590276-7d632180-6527-11ea-8ba0-56eba0806466.png)
> 不可能的啊，这个选项0.0.1就有了，你是不是从release下载的？

是release下的
![Snipaste_2020-03-13_12-40-23](https://user-images.githubusercontent.com/1650525/76590405-e9458a00-6527-11ea-89ae-f0febab363a2.png)
![Snipaste_2020-03-13_12-39-40](https://user-images.githubusercontent.com/1650525/76590410-ec407a80-6527-11ea-8836-f7e331f6a6b6.png)

**Comment by neverno** [comment]
> ![QQ20200313-123745](https://user-images.githubusercontent.com/39617891/76590276-7d632180-6527-11ea-8ba0-56eba0806466.png)
> 不可能的啊，这个选项0.0.1就有了，你是不是从release下载的？

抱歉，我找错地方了，从文件那是有，但右键新增那没有~

**Comment by TheWanderingCoel** [comment]
确实，右键新建是连接的菜单，不是文件的。

**Comment by neverno** [comment]
> 确实，右键新建是连接的菜单，不是文件的。

感谢~

**Comment by TheWanderingCoel** [comment]
没事~
