### ISSUE TITLE
期待作者继续抽用自己的宝贵时间进一步更新mac版的客户端

### ISSUE THREAD

**Issue by sidoinefr** [TheWanderingCoel/Trojan-Qt5#182]
0.04a已经正常使用了一段时间，虽然还是有些小问题，但是并不影响正常使用，非常感谢作者前一段的高效率工作，满足了我们这些素未谋面用户的使用需求。还是希望作者能在有可能的情况下，逐步跟进和更新客户端的目前的不完美，使之变成Trojan上最牛的客户端，就像小火箭一样，占据基本全部江山，用户量有了基础，后面软件完善中需要的很多资源必定会慢慢丰富起来，提前感谢作者！

**Comment by TheWanderingCoel** [comment]
感谢支持~新功能正在路上...

**Comment by TheWanderingCoel** [comment]
尝试下004b?

**Comment by TheWanderingCoel** [comment]
008已推出，先关闭了
