### ISSUE TITLE
自动更新弹出对话框有新版本可以升级，但是不能正常显示Release Notes，也不能正常安装更新

### ISSUE THREAD

**Issue by terryl213** [TheWanderingCoel/Trojan-Qt5#189]
自动更新弹出对话框有新版本可以升级，但是不能正常显示Release Notes，也不能正常安装更新。

显示版本2.0已经上线，但并不能正常升级。

![image](https://user-images.githubusercontent.com/24470164/76635432-70bfe700-6582-11ea-8eb7-90b29f1d5aff.png)

**Comment by TheWanderingCoel** [comment]
目前自动更新只是一个壳子，现在更新方式还是只有release一个渠道。实在抱歉，会尽快实现

**Comment by terryl213** [comment]
多谢回复。
