### ISSUE TITLE
自动化选项Bug

### ISSUE THREAD

**Issue by DeviesVi** [TheWanderingCoel/Trojan-Qt5#19]
自动化选项中，程序启动时自动连接勾选后，仍然不会在程序启动时自动连接。

**Comment by TheWanderingCoel** [comment]
我把它注释掉了，本来想着这个功能没人用就想删掉的。下个commit我把它取消注释。

**Comment by TheWanderingCoel** [comment]
https://github.com/TheWanderingCoel/Trojan-Qt5/blob/f13bff0c4d7cd1235c148850bb6acf5caf865348/src/confighelper.cpp#L393

**Comment by TheWanderingCoel** [comment]
已取消注释
