### ISSUE TITLE
Mac V0.0.4b 体验

### ISSUE THREAD

**Issue by moqimoqidea** [TheWanderingCoel/Trojan-Qt5#191]
* 界面不糊了，很强 +1。
* Dock 栏可以呼出了，很强 +1。
* PAC 支持更全面了，很强 +1。

🍻🍻🍻

**Comment by dr1llc4t** [comment]
之前不是achieved的了么，我以为不更了

**Comment by TheWanderingCoel** [comment]
> * 界面不糊了，很强 +1。
> * Dock 栏可以呼出了，很强 +1。
> * PAC 支持更全面了，很强 +1。
> 
> 🍻🍻🍻

哈哈哈，谢谢~

**Comment by TheWanderingCoel** [comment]
> 之前不是achieved的了么，我以为不更了

身体不舒服，歇了一阵子

**Comment by dr1llc4t** [comment]
> > 之前不是achieved的了么，我以为不更了
> 
> 身体不舒服，歇了一阵子
提个小建议，Mac上字体不糊了，但是图片还是糊的。

**Comment by TheWanderingCoel** [comment]
> > > 之前不是achieved的了么，我以为不更了
> > 
> > 
> > 身体不舒服，歇了一阵子
> > 提个小建议，Mac上字体不糊了，但是图片还是糊的。

收到,稍后研究下

**Comment by moqimoqidea** [comment]
都出 v0.0.4c 了，我去体验下。

**Comment by TheWanderingCoel** [comment]
> 都出 v0.0.4c 了，我去体验下。

v0.0.4c修复了一些小bug
