### ISSUE TITLE
在任务栏菜单更新PAC后必须重新连接，否则不生效

### ISSUE THREAD

**Issue by Atom2004** [TheWanderingCoel/Trojan-Qt5#192]
![Annotation 2020-03-14 170350](https://user-images.githubusercontent.com/22042246/76678831-2720dc00-6616-11ea-810e-61219637b35c.png)

用如图的方式更新PAC后，必须手动重新连接，PAC的更改才能生效。
既然手动在菜单中更新的PAC，能否自动将PAC重新加载到内存？或者自动重新连接一下？

老以为我填写的user-rule格式有问题，后来才发现需要重新连接才能生效。

**Comment by TheWanderingCoel** [comment]
我也发现了这一点，尝试在系统设置里关掉代理，在重新填写pac地址就好了。我觉得是系统自动缓存了pac的内容。下一个版本切换PAC自动重新设置一下系统代理

**Comment by TheWanderingCoel** [comment]
004c应该修复

**Comment by TheWanderingCoel** [comment]
有问题欢迎随时反馈
