### ISSUE TITLE
0.0.4b更改代理需重启生效

### ISSUE THREAD

**Issue by jdleung** [TheWanderingCoel/Trojan-Qt5#193]
新版本在使用上方便了不少，赞！

在使用中发现，如果要更改服务器地址，上一个版本直接选服务器后，App会自动停止正在使用的服务器，然后启动新的。但最新版本的App停止了正在使用的服务器后无法连接新的服务器，手动点击也无效，必需重新启动App。是否一个bug？谢谢

**Comment by TheWanderingCoel** [comment]
嗯，我也时不时会遇到。感觉有点问题，下一个版本会修复

**Comment by TheWanderingCoel** [comment]
如果可以的话，是否能提供下gui日志呢？

**Comment by TheWanderingCoel** [comment]
看样子是privoxy的端口没有被释放导致的

**Comment by TheWanderingCoel** [comment]
忘改停止时的代码了,尴尬...

**Comment by TheWanderingCoel** [comment]
已修复，十分感谢提出此bug

**Comment by jdleung** [comment]
看了一下GUI日志，应该是这两行吧
2020-03-15 10:03:03.228 ERROR [62861] [Logger::error@47] The bound address is already in use
2020-03-15 10:03:03.229 ERROR [62861] [Logger::error@47] Http port 1081 is being used

不过，你这么快已经查到了就不用了。

**Comment by TheWanderingCoel** [comment]
还是感谢了。试试004c，应该没有这个问题了

**Comment by TheWanderingCoel** [comment]
有问题欢迎随时反馈

**Comment by jdleung** [comment]
嗯，已经在用，问题已解决。谢谢
