### ISSUE TITLE
V0.0.4C http端口断开连接后不能释放

### ISSUE THREAD

**Issue by left3721** [TheWanderingCoel/Trojan-Qt5#195]
系统：Ubuntu18.04
版本：V0.0.4C
操作过程：正常连接一个服务器后，再断开，重接连一个新服务器连接按钮灰色不能点，netstat -ntlp看到http端口没释放

**Comment by TheWanderingCoel** [comment]
内置的privoxy好像有问题，privoxy无法释放端口，linux可以关闭http模式
