### ISSUE TITLE
The Windows client fails to start up

### ISSUE THREAD

**Issue by reee** [TheWanderingCoel/Trojan-Qt5#2]
It shows "libcrypto-1_1.dll is missing" and "libssl-1_1.dll is missing"
after i put theses two dll files into the dictionary, It all OK.
So maybe you should pack theses two files into the installer?

**Comment by TheWanderingCoel** [comment]
Sure. I have just updated a commit that will automatically download it from ``Trojan-Qt5-Dll`` repo. Thanks for advice

**Comment by TheWanderingCoel** [comment]
Finished. If you have any issue, please feel free to reopen it / open a new one.
