### ISSUE TITLE
[Feature Request] i了i了

### ISSUE THREAD

**Issue by 1725636955** [TheWanderingCoel/Trojan-Qt5#218]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheWanderingCoel** [comment]
？？？

**Comment by 1725636955** [comment]
> ？？？

爱了爱了

**Comment by TheWanderingCoel** [comment]
感谢支持，交流可以添加tg群@TrojanQt5,不用发issue hhh

**Comment by 1725636955** [comment]
> 感谢支持，交流可以添加tg群@TrojanQt5,不用发issue hhh

好的
