### ISSUE TITLE
0.0.5 版本下载报病毒

### ISSUE THREAD

**Issue by jfdnet** [TheWanderingCoel/Trojan-Qt5#225]
下载不成功 报病毒

![Annotation 2020-03-25 095113](https://user-images.githubusercontent.com/1990429/77493536-61904180-6e7e-11ea-941a-17199c03dcdf.jpg)
![Annotation 2020-03-25 095050](https://user-images.githubusercontent.com/1990429/77493537-62c16e80-6e7e-11ea-8ffe-8d80beb42ed5.jpg)

**Comment by TheWanderingCoel** [comment]
@jfdnet 微软经典瞎报毒，信任即可，所有release通过ci自动编译，hash可以追踪，无毒

**Comment by jfdnet** [comment]
好的谢谢
