### ISSUE TITLE
Win10下，连接自动闪退

### ISSUE THREAD

**Issue by Badalin** [TheWanderingCoel/Trojan-Qt5#23]
请问点了连接，然后这个软件自动关闭闪退，怎么回事？

**Comment by TheWanderingCoel** [comment]
路径不能有中文和空格

**Comment by Badalin** [comment]
> 路径不能有中文和空格

哪的路径，能不能说详细点？

**Comment by TheWanderingCoel** [comment]
就是``trojan-qt5.exe``的路径不能空格和中文。
这样就不行  
``C:\Program Files\Trojan-Qt5\trojan-qt5.exe``
这样也不行  
``D:\程序\Trojan-Qt5\trojan-qt5.exe``
