### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EA-DICE** [TheWanderingCoel/Trojan-Qt5#232]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.

**Trojan-Qt5 Version**
0.0.5

**Describe the bug**
在windows10系统（1909最新版本）下，windows defender报毒

**To Reproduce**
运行就会报毒并且阻止启动
**Expected behavior**
正常启动且最好不报毒
**GUI Log**
If applicable, add GUI Log to help explain your problem.

**Trojan Log**
If applicable, add Trojan log to help explain your problem

**Environment**
What is your operating system? Specific desktop Environment and distribution when you are using Linux.
windows10（18363.152）64bit
**Additional context**

![捕获](https://user-images.githubusercontent.com/42771283/77614586-4b5eb000-6f68-11ea-9e41-eb9db53b8e8e.PNG)

**Comment by TheWanderingCoel** [comment]
@EA-DICE 添加信任即可,报毒我也不知道怎么解决。从0.0.1 Windows就开始报毒了

**Comment by EA-DICE** [comment]
很奇怪，我是从0.0.5才开始出现这种情况

**Comment by EA-DICE** [comment]
> @EA-DICE 添加信任即可,报毒我也不知道怎么解决。从0.0.1 Windows就开始报毒了

好吧，既然有解决办法了就关这个issue了吧

**Comment by TheWanderingCoel** [comment]
@EA-DICE 抱歉，杀毒软件不是我能控制的

**Comment by EA-DICE** [comment]
> @EA-DICE 抱歉，杀毒软件不是我能控制的

没关系，我知道这和软件本身无关
