### ISSUE TITLE
[BUG]sni config not effect

### ISSUE THREAD

**Issue by cybmp3** [TheWanderingCoel/Trojan-Qt5#234]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.

**Trojan-Qt5 Version**
The version of trojan you are using.
0.0.5
**Describe the bug**
I can’t connect to the trojan server by filling the domain name in the sni field.
And I check the trojan.json there is nothing at sni field.
![20200326174338](https://user-images.githubusercontent.com/14276116/77632801-7a394e00-6f89-11ea-8c6f-c4c6efb2c006.png)

**To Reproduce**

**Expected behavior**

**GUI Log**
If applicable, add GUI Log to help explain your problem.

**Trojan Log**
If applicable, add Trojan log to help explain your problem

**Environment**
What is your operating system? Specific desktop Environment and distribution when you are using Linux.

**Additional context**

**Comment by TheWanderingCoel** [comment]
@cybmp3 Confirmed and will be fixed in v0.0.6

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3 Confirmed and will be fixed in v0.0.6

so fast...
Actually I am going to write the code to help you fix it.

**Comment by TheWanderingCoel** [comment]
@cybmp3 in confighelper.cpp, change `ssl["sni"] = "";` to `ssl["sni"] = profile.sni;` resolved this issue. I'm to hurry to publish v0.0.5 so ignore this field, sorry for that.

**Comment by cybmp3** [comment]
let me do it .
keep healthy.

**Comment by TheWanderingCoel** [comment]
close as finished
