### ISSUE TITLE
[BUG] 访问hub5btmain.sandai.net的作用

### ISSUE THREAD

**Issue by ssc19940105** [TheWanderingCoel/Trojan-Qt5#237]
程序访问hub5btmain.sandai.net这个无关地址的作用

**Comment by TheWanderingCoel** [comment]
@ssc19940105 程序全开源，没有任何恶意操作

**Comment by ssc19940105** [comment]
这个服务器是迅雷的，我实在想不出访问这个地址的作用

**Comment by TheWanderingCoel** [comment]
全局代理迅雷走了代理，你应该问迅雷为啥访问这个网站

**Comment by ssc19940105** [comment]
我计算机上没有安装迅雷，还有这个地址是Trojan-Qt访问的

**Comment by ssc19940105** [comment]
因此我这边感到很困惑

**Comment by TheWanderingCoel** [comment]
@ssc19940105 你是release下的，checksum了吗？如果checksum不符合，我怀疑你的安装包被植入了病毒

**Comment by TheWanderingCoel** [comment]
@TheWanderingCoel 可以搜索全部全部源代码，没有这个网站

**Comment by TheWanderingCoel** [comment]
@TheWanderingCoel https://ci.appveyor.com/project/CoelWu/trojan-qt5/builds/31680905

**Comment by ssc19940105** [comment]
是Release里面下的，目前正在检查哈希

**Comment by coderstory** [comment]
也可以能使用了迅雷sdk的软件

**Comment by TheWanderingCoel** [comment]
@coderstory 嗯，不是没可能。让他看下日志，有accpeted这个地址就是别的软件访问的，与此软件无关

**Comment by ssc19940105** [comment]
@TheWanderingCoel @coderstory 原因已经找到了。我之前为了屏蔽迅雷的敏感词。我将这个域名的IP指向了127.0.0.1。由于资源管理器的BUG，会将所有的127.0.0.1显示为这个域名。我删除了对应的Hosts记录重启之后就解决了。

**Comment by ssc19940105** [comment]
感谢各位

**Comment by TheWanderingCoel** [comment]
@ssc19940105 没事，我还以为有病毒。。。心情有点暴躁
