### ISSUE TITLE
[BUG]win10任务栏图标双击无法打开

### ISSUE THREAD

**Issue by onlyJinx** [TheWanderingCoel/Trojan-Qt5#238]
不知道是我电脑问题还是软件问题~

![image](https://user-images.githubusercontent.com/21324835/77718779-ae128300-701e-11ea-9684-bfafd11c4674.png)
![image](https://user-images.githubusercontent.com/21324835/77718802-b8348180-701e-11ea-824c-d9284fa8c116.png)

**Comment by TheWanderingCoel** [comment]
这个feature被我remove了，看情况加回来

**Comment by onlyJinx** [comment]
OK, thanks.
