### ISSUE TITLE
trojan客户端会和ss客户端冲突吗？

### ISSUE THREAD

**Issue by killingangelcn** [TheWanderingCoel/Trojan-Qt5#24]
刚从ss转的trojan，trojan客户端这边都已经设置好了，服务器也连接好了，但是在chrome+switchyomega的配置下，代理设为127.0.0.1:1080什么网页都打不开，ss客户端已经退出了，难道说要彻底从系统里删除才可以吗？

**Comment by TheWanderingCoel** [comment]
不需要删除``ss-qt5``检查下你的服务器设置是否正确，跟``ss-qt5``不冲突。试试``lsof -i:1080``看看什么在占用端口

**Comment by TheWanderingCoel** [comment]
> 刚从ss转的trojan，trojan客户端这边都已经设置好了，服务器也连接好了，但是在chrome+switchyomega的配置下，代理设为127.0.0.1:1080什么网页都打不开，ss客户端已经退出了，难道说要彻底从系统里删除才可以吗？

试试``v0.0.3``

**Comment by TheWanderingCoel** [comment]
close due to inactivity. Feel free to submit a new one as you want.
