### ISSUE TITLE
windows10不能访问外网

### ISSUE THREAD

**Issue by yqtx528** [TheWanderingCoel/Trojan-Qt5#240]
<h1>Trojan-Qt5</h1><p><b>Version 0.0.5</b><br/>Using trojan 1.15.0, Privoxy 3.0.28 Binary<br>Boost 1_72, OpenSSL 1.1.1e  17 Mar 2020<br>LibQREncode 3.4.4</p><p>Copyright © 2014-2018 Symeon Huang (<a href='https://twitter.com/librehat'>@librehat</a>)</p><p>Copyright © 2019-2020 TheWanderingCoel (<a href='https://github.com/TheWanderingCoel'>@TheWanderingCoel</a>)</p><p>License: <a href='http://www.gnu.org/licenses/gpl.html'>GNU General Public License Version 3</a><br />Project Hosted at <a href='https://github.com/TheWanderingCoel/Trojan-Qt5'>GitHub</a><br />Telegram Group <a href='https://t.me/TrojanQt5'>@TrojanQt5</a><br />Telegram Channel <a href='https://t.me/TrojanQt5News'>@TrojanQt5News</a></p>

```
[2020-03-27 13:52:37] [ERROR] 127.0.0.1:52756 SSL handshake failed with nl1-1.sstr-api.xyz:443: certificate verify failed
```

**Comment by TheWanderingCoel** [comment]
关闭验证证书
