### ISSUE TITLE
[BUG] 一个小bug

### ISSUE THREAD

**Issue by Itzamana** [TheWanderingCoel/Trojan-Qt5#245]
软件菜单栏 设置-用户规则设置 点击OK保存后，再次打开就会出现乱码…

![](https://pic.downk.cc/item/5e7fe1fa504f4bcb04e2b5e8.png)

**Comment by TheWanderingCoel** [comment]
可能是Windows的问题，下个版本预计修复

**Comment by TheWanderingCoel** [comment]
已修复
