### ISSUE TITLE
连上了，但是刷网页，比如Google或Youtube，不能一次就刷开。

### ISSUE THREAD

**Issue by Badalin** [TheWanderingCoel/Trojan-Qt5#25]
有时，要连刷很多次才能刷开。刷不开的时候，则显示：

无法访问此网站

**Comment by TheWanderingCoel** [comment]
什么系统环境呢？服务器是哪里的？我这里没有问题，服务器用的CN2 GIA的。

**Comment by Badalin** [comment]
> 什么系统环境呢？服务器是哪里的？我这里没有问题，服务器用的CN2 GIA的。

Win10，JP6服务器，然后想再chrome里更新Proxy SwitchyOmega插件也更新不起，一直显示：正在更新。。。

**Comment by TheWanderingCoel** [comment]
v0.0.2的话默认会设置http代理的，试试不用SwitchyOmega？
