### ISSUE TITLE
ubuntu18运行问题，提示需要额外的mine类型支持

### ISSUE THREAD

**Issue by ReadRou** [TheWanderingCoel/Trojan-Qt5#253]
# 版本
Trojan-Qt5-Linux-0.0.5-20200322

# 系统
![image](https://user-images.githubusercontent.com/30749019/77997125-73338680-7361-11ea-9c22-8940ab14df50.png)

# 错误提示

1.双击打开
![image](https://user-images.githubusercontent.com/30749019/77997178-88101a00-7361-11ea-97ef-539352b994e7.png)

2.提示需要额外的mine类型支持
![image](https://user-images.githubusercontent.com/30749019/77997233-a0803480-7361-11ea-999b-5b3bfcfdbd82.png)

**Comment by TheWanderingCoel** [comment]
@ReadRou 终端./名字.AppImage

**Comment by sherlockwho** [comment]
右键、属性、添加可执行权限

**Comment by ReadRou** [comment]
我可以打开软件了，但是无法进行代理。

1。trojan设置

![image](https://user-images.githubusercontent.com/30749019/78100092-6f157080-7416-11ea-8437-46d32c36ee8c.png)


2。网路代理设置
trojan-qt5自动设置的（http://127.0.0.1:8070/proxy.pac）
![image](https://user-images.githubusercontent.com/30749019/78100151-8a807b80-7416-11ea-8025-66f1a0030f1e.png)

3。代理模式
![image](https://user-images.githubusercontent.com/30749019/78100404-46da4180-7417-11ea-8ccc-7a9156099f48.png)



4。结果
![image](https://user-images.githubusercontent.com/30749019/78100304-fb279800-7416-11ea-9200-dd030ff22522.png)

**Comment by sherlockwho** [comment]
那我和你一样，我前两天也发过一个issue讲Linux客户端的连接，有一部分节点可以连接，大部分不行，现在还没有解决。

**Comment by ReadRou** [comment]
> 那我和你一样，我前两天也发过一个issue讲Linux客户端的连接，有一部分例程可以连接，大部分不行，现在还没有解决。

issues编号是多少个

**Comment by TheWanderingCoel** [comment]
@ReadRou 日志呢？

**Comment by sherlockwho** [comment]
> > 那我和你一样，我前两天也发过一个issue讲Linux客户端的连接，有一部分例程可以连接，大部分不行，现在还没有解决。
> 
> issues编号是多少个

#247

**Comment by ReadRou** [comment]
查看trojan的日志，发现和服务器握手失败

![image](https://user-images.githubusercontent.com/30749019/78101482-3aa3b380-741a-11ea-9e38-e5e123c9a54a.png)
试了几个服务器都是这样。

**Comment by TheWanderingCoel** [comment]
@ReadRou 关闭验证证书即可，linux基本需要指定证书路径/关闭验证证书

**Comment by ReadRou** [comment]
> @ReadRou关闭验证证书即可，linux基本需要指定证书路径/关闭验证证书

好的，铁子，已经可以了。流批

![164824927](https://user-images.githubusercontent.com/30749019/78102018-cec24a80-741b-11ea-90e6-cb087f477161.jpg)

**Comment by rzlq** [comment]
> > @ReadRou关闭验证证书即可，linux基本需要指定证书路径/关闭验证证书
> 
> 好的，铁子，已经可以了。流批
> 
> ![164824927](https://user-images.githubusercontent.com/30749019/78102018-cec24a80-741b-11ea-90e6-cb087f477161.jpg)

请问该怎么关闭验证证书，我也遇到了这个问题。

**Comment by TheWanderingCoel** [comment]
@rzlq 点编辑，里面就有

**Comment by ReadRou** [comment]
铁子，我关闭issues了，3q
