### ISSUE TITLE
连接成功但打不开网页

### ISSUE THREAD

**Issue by bomersyx** [TheWanderingCoel/Trojan-Qt5#26]
MAC环境，用os1-1、os1-5、hk1-3连接都有latency速度，也显示已连接，但网页打不开。

**Comment by TheWanderingCoel** [comment]
检测下代理有没有设置上?我环境就是mac,没有问题

**Comment by left3721** [comment]
我Ubuntu18.04 也有这个问题 在命令行下连同一个结点是可以打开网页的，换成Trojan-Qt5只能偶尔打开一下网页

**Comment by TheWanderingCoel** [comment]
我研究下，这个问题汇报的还是很频繁。。。我推送下0.0.3有日志可以更好分析问题。

**Comment by bomersyx** [comment]
> 检测下代理有没有设置上?我环境就是mac,没有问题

代理如何设置？

**Comment by TheWanderingCoel** [comment]
系统偏好设置，网络，Wi-Fi，高级设置，代理

**Comment by bomersyx** [comment]
> 系统偏好设置，网络，Wi-Fi，高级设置，代理

http、https、socks都是勾选上的，其余未勾，不过勾上貌似也打不开网页。还有“自动发现代理、自动代理配置、FTP、RTSP、Gopher代理”

**Comment by TheWanderingCoel** [comment]
我马上推送0.0.3，看下日志我应该知道什么情况了。

**Comment by TheWanderingCoel** [comment]
> > 系统偏好设置，网络，Wi-Fi，高级设置，代理
> 
> http、https、socks都是勾选上的，其余未勾，不过勾上貌似也打不开网页。还有“自动发现代理、自动代理配置、FTP、RTSP、Gopher代理”

请尝试下``v0.0.3``

**Comment by TheWanderingCoel** [comment]
这个issue先关了。有问题在你那个新的issue回复吧。
