### ISSUE TITLE
[BUG]关于订阅系统～

### ISSUE THREAD

**Issue by sindy0608** [TheWanderingCoel/Trojan-Qt5#262]
您好，请问下订阅系统是否有相关文档，我适配的订阅输出格式没问题，但是无法成功订阅

**Comment by TheWanderingCoel** [comment]
已修复订阅问题

**Comment by sindy0608** [comment]
非常感谢。 测试后已经可以成功订阅，另外请问下是否有支持emoji编码的计划呢，这样可以显示服务器国旗

**Comment by TheWanderingCoel** [comment]
应该是支持的，不知道为啥ci编译的版本就不支持emoji。
