### ISSUE TITLE
对作者说几句真心话

### ISSUE THREAD

**Issue by EA-DICE** [TheWanderingCoel/Trojan-Qt5#265]
首先，真的非常感谢作者，为大伙贡献出了自己的时间和精力，真的得向作者致谢。我看了CrystalIDEA工程师提的issue，也看了作者的release notes，大概了解了是怎么回事，我能感觉到作者在前段时间应该压力也挺大的，希望能够放下沉重的包袱，之前作者也说自己身体不太好，我在这也衷心祝愿作者身体健康，万事如意。

**Comment by TheWanderingCoel** [comment]
@EA-DICE 感谢！那次确实是我的疏忽，跟大家再次说一声抱歉。

**Comment by EA-DICE** [comment]
![image](https://user-images.githubusercontent.com/42771283/78419246-89e62000-7676-11ea-9a58-9e1e0b9b5cb1.png)
还有个小问题，之前一直不太懂这些选项的意义，有时间可以帮我讲讲是什么意思吗

**Comment by EA-DICE** [comment]
> @EA-DICE 感谢！那次确实是我的疏忽，跟大家再次说一声抱歉。

真的，我能感觉到作者身上的压力

**Comment by TheWanderingCoel** [comment]
@EA-DICE PAC模式的选择，跟shadowsocks(rr)-windows一样，用过的话应该比较熟悉，推荐gfwlist就行了

**Comment by EA-DICE** [comment]
绕过大陆常见域名的意思是不是默认全局代理，发现大陆的域名就走直连

**Comment by TheWanderingCoel** [comment]
@EA-DICE 就是大陆常见的域名直连，其他走代理

**Comment by EA-DICE** [comment]
我之前用gfwlist，有部分网站访问不了，gfwlist好久也没更新了

**Comment by EA-DICE** [comment]
> @EA-DICE 就是大陆常见的域名直连，其他走代理

那要不要选增强域名列表

**Comment by TheWanderingCoel** [comment]
@EA-DICE 实验性功能，慎选

**Comment by EA-DICE** [comment]
如果选gfwlist是黑名单机制还是白名单机制

**Comment by EA-DICE** [comment]
用gfwlist的话GitHub图片加载不出

**Comment by TheWanderingCoel** [comment]
@EA-DICE 因为github没被墙啊

**Comment by EA-DICE** [comment]
那这个大陆常见域名列表可以手动检查更新吗

**Comment by EA-DICE** [comment]
好的好的，谢谢作者细心解答

**Comment by zhibinr** [comment]
> 用gfwlist的话GitHub图片加载不出

因为 github.com 没被墙，但是 *.avatars0.githubusercontent.com 之类的被墙了
