### ISSUE TITLE
[BUG] windows 每次开机都会默认为“全局模式”，如何改成“PAC模式”？

### ISSUE THREAD

**Issue by ANGELMARS** [TheWanderingCoel/Trojan-Qt5#266]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.

**Trojan-Qt5 Version**
0.0.6 windows10

**Describe the bug**
 每次开机都会默认为“全局模式”，如何改成默认为“PAC模式”？懒得每次都要手动点一下。

**Comment by TheWanderingCoel** [comment]
@ANGELMARS 照理改了一次就会默认的,0.0.6存在bug,稍后发007
