### ISSUE TITLE
[BUG]使用Trojan链接导入服务器时服务器名称显示为乱码

### ISSUE THREAD

**Issue by EA-DICE** [TheWanderingCoel/Trojan-Qt5#267]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.

**Trojan-Qt5 Version**
0.0.7

**Describe the bug**
使用Trojan链接导入服务器时服务器名称显示为乱码

**To Reproduce**
如题

**Expected behavior**
正常显示

**GUI Log**
If applicable, add GUI Log to help explain your problem.

**Trojan Log**
If applicable, add Trojan log to help explain your problem

**Environment**
windows 10 64bit

**Additional context**

**Comment by TheWanderingCoel** [comment]
稍后修复

**Comment by EA-DICE** [comment]
好的，此bug已在最新版本（0.0.7）中得到修复，感谢作者
