### ISSUE TITLE
有的服务器还是有问题，一些大众网站访问不了。

### ISSUE THREAD

**Issue by Badalin** [TheWanderingCoel/Trojan-Qt5#27]
日本，德国，香港，爱沙尼亚服务器在Win10下都访问不了：
http://www.weebly.com/
https://www.worldcat.org/
其中，日本的连
https://en.wikipedia.org/
都不行。

失败理由都是 ERR_CONNECTION_TIMED_OUT

**Comment by TheWanderingCoel** [comment]
服务器试试安装``bbr plus``?有没有服务器可以正常都访问的。。。有点感觉是不是我客户端有问题。
