### ISSUE TITLE
[BUG]Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by aslongaspossible** [TheWanderingCoel/Trojan-Qt5#278]
v0.0.8 被Windows defender强制删除了，报的是Trojan:Win32/Wacatac.B!ml
实际上我已经用了一两天了，今天突然报了个错。想想我这几天也就只是多了个订阅浏览器这个操作。

**Comment by TheWanderingCoel** [comment]
手动添加排除项即可
