### ISSUE TITLE
客户端连接闪退

### ISSUE THREAD

**Issue by vonzate** [TheWanderingCoel/Trojan-Qt5#28]
环境为win10，配置完毕服务器后点击连接，然而程序闪退，图标消失。是trojan与什么程序冲突了么

**Comment by TheWanderingCoel** [comment]
``trojan-qt5``路径不能有中文和空格

**Comment by cnyiwei** [comment]
换成英文路径还是闪退。

**Comment by cnyiwei** [comment]
最后放根目录正常运行。

**Comment by TheWanderingCoel** [comment]
> 最后放根目录正常运行。

感谢反馈，稍后可以试一下``v0.0.3``

**Comment by TheWanderingCoel** [comment]
close due to inactivity. Feel free to submit a new one as you want.
