### ISSUE TITLE
[BUG] 无法开启Trojan

### ISSUE THREAD

**Issue by KingAmo** [TheWanderingCoel/Trojan-Qt5#281]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.

**Trojan-Qt5 Version**
`0.0.8`

**Describe the bug**
ui界面不知怎么的变成这样子了，
[image](https://user-images.githubusercontent.com/29938227/78754707-86220880-79aa-11ea-87ee-b0e363e1ea8b.png)
`打开trojan`按钮没反应，也无法连接节点
![image](https://user-images.githubusercontent.com/29938227/78754741-976b1500-79aa-11ea-8641-a7e21203aaed.png)

**To Reproduce**

**Expected behavior**

**GUI Log**
If applicable, add GUI Log to help explain your problem.

**Trojan Log**
If applicable, add Trojan log to help explain your problem

**Environment**
What is your operating system? Specific desktop Environment and distribution when you are using Linux.

**Additional context**

**Comment by TheWanderingCoel** [comment]
请发出日志

**Comment by KingAmo** [comment]
请问如何查看日志？
![image](https://user-images.githubusercontent.com/29938227/78760105-3dbb1880-79b3-11ea-8286-50669ce55e0a.png)
切换到 ui 界面，顶部的导航栏仍是上一个应用（Chrome）的导航栏，也就是说，无法显示`Trojan-Qt5`的导航栏了

**Comment by TheWanderingCoel** [comment]
@KingAmo command 加 , 打开设置，关闭原生菜单栏和隐藏图标重启软件

**Comment by KingAmo** [comment]
@TheWanderingCoel  谢谢，gui log 提示socks 5的端口被占用，换了个端口后可以开启 `Trojan`, 但是 pac模式无效，全局模式正常。。。

**Comment by TheWanderingCoel** [comment]
你把pac端口也换一个，重启软件吧…估计8070也占用了

**Comment by KingAmo** [comment]
十分感谢！！

**Comment by KingAmo** [comment]
总结一下，主要是我装了多个翻墙软件，监听的端口有冲突。但是奇怪的是，我关掉了其他软件，保留一个软件运行，还是有冲突，直到我改了端口才解决...
