### ISSUE TITLE
Recognized as a junkware in Windows 10

### ISSUE THREAD

**Issue by aidistan** [TheWanderingCoel/Trojan-Qt5#3]
![图片](https://user-images.githubusercontent.com/3037661/74404363-3a008f00-4e65-11ea-9012-a6b0525c6bf9.png)

**Comment by TheWanderingCoel** [comment]
One of my friend also have this problem, Currently I have no idea why it was junkware. The binary release were compiled from ``travis-ci`` and ``appveyor``. It's completely safe.

**Comment by TheWanderingCoel** [comment]
I believe it's an accident report. Check this out. [Link](https://www.virustotal.com/gui/file/247faa5d67592af7583a7ebd53654383d25e258de329ee145f7d8abbf2ba7034/detection)

**Comment by TheWanderingCoel** [comment]
You can also try to compile it from sources. This project is fully opensource. That is one of reasons that I open source.

**Comment by aidistan** [comment]
I completely understand the situation. But I hope this could be fixed in the near future to make your project more acceptable for green hands 😄

**Comment by TheWanderingCoel** [comment]
> I completely understand the situation. But I hope this could be fixed in the near future to make your project more acceptable for green hands 😄

Sure. But I'm afraid I can't do anything to resolve that. Maybe I should try to reach Microsoft Defender Team to solve this. Thanks for your report so much!

**Comment by TheWanderingCoel** [comment]
I have added ``md5`` and ``sha1`` hashes. So you can check the hash after you download it.

**Comment by babylife** [comment]
i do not have such issue

**Comment by TheWanderingCoel** [comment]
> i do not have such issue

V0.0.2 does not have this issue. I don't know what's wrong with v0.0.1

**Comment by hyq3351** [comment]
V0.0.2仍然被defender检测，手动信任，添加节点后点连接直接闪退，无任何提示，请问什么问题

**Comment by TheWanderingCoel** [comment]
> @TheWanderingCoel V0.0.2仍然被defender检测，手动信任，添加节点后点连接直接闪退，无任何提示，请问什么问题

直接闪退么，有没有什么报错？

**Comment by TheWanderingCoel** [comment]
V0.0.2的结果，我还是不知道为啥报毒...[Link](https://www.virustotal.com/gui/file/4f73d88689b13d46f087bccb6ed7da3935917e1980e80e8c92de64e081b6a537/detection)

**Comment by hyq3351** [comment]
> > @TheWanderingCoel V0.0.2仍然被defender检测，手动信任，添加节点后点连接直接闪退，无任何提示，请问什么问题
> 
> 直接闪退么，有没有什么报错？

没任何提示，直接会闪退

**Comment by TheWanderingCoel** [comment]
> > @TheWanderingCoel V0.0.2仍然被defender检测，手动信任，添加节点后点连接直接闪退，无任何提示，请问什么问题

可否在命令行下运行，应该会有一些提示。没提示，日志的话我不太好判断什么情况。``trojan-qt5.exe``在命令行里启动

**Comment by hyq3351** [comment]
> @hyq3351
> 可否在命令行下运行，应该会有一些提示。没提示，日志的话我不太好判断什么情况。`trojan-qt5.exe`在命令行里启动

现在搞好了 麻烦了 谢谢

**Comment by TheWanderingCoel** [comment]
> > 可否在命令行下运行，应该会有一些提示。没提示，日志的话我不太好判断什么情况。`trojan-qt5.exe`在命令行里启动

没事，如果以后有不同的bug可以新开一个issue。我看到会回复的

**Comment by yjw-the-one** [comment]
> > @hyq3351
> > 可否在命令行下运行，应该会有一些提示。没提示，日志的话我不太好判断什么情况。`trojan-qt5.exe`在命令行里启动
> 
> 现在搞好了 麻烦了 谢谢

我也是闪退的问题，请问你是如何解决的，

**Comment by TheWanderingCoel** [comment]
> > > @hyq3351
> > > 可否在命令行下运行，应该会有一些提示。没提示，日志的话我不太好判断什么情况。`trojan-qt5.exe`在命令行里启动
> > 
> > 
> > 现在搞好了 麻烦了 谢谢
> 
> 我也是闪退的问题，请问你是如何解决的，

目录不能有中文和空格，请尝试下``v0.0.3``应该修复了

**Comment by TheWanderingCoel** [comment]
> I completely understand the situation. But I hope this could be fixed in the near future to make your project more acceptable for green hands 😄

Microsoft's false positive seem to be solved now :D. Only Trapmine will detect, but I think trapmine is not so popular. Closing this issue for now.
