### ISSUE TITLE
proxy mode

### ISSUE THREAD

**Issue by avalond** [TheWanderingCoel/Trojan-Qt5#30]
proxy mode 
1.  rule ---> maybe can compatible shadowsocket rules
2. global
3. direct

**Comment by TheWanderingCoel** [comment]
> proxy mode
> 
> 1. rule ---> maybe can compatible shadowsocket rules
> 2. global
> 3. direct

Rule is only ``pac`` now, global and direct have been implemented. Add a paster for shadowrocket rules and also make changes in trojan code will be very harder. Will consider this future later.

**Comment by avalond** [comment]
> > proxy mode
> > 
> > 1. rule ---> maybe can compatible shadowsocket rules
> > 2. global
> > 3. direct
> 
> Rule is only `pac` now, global and direct have been implemented. Add a paster for shadowrocket rules and also make changes in trojan code. Which will be very hard to achieve. Will consider this future later.

Thank you for your work

**Comment by TheWanderingCoel** [comment]
You’re welcome. Feel free to open another issue if you have any problem.
