### ISSUE TITLE
客户端切换节点连接闪退

### ISSUE THREAD

**Issue by left3721** [TheWanderingCoel/Trojan-Qt5#31]
系统：Ubuntu 18.04.4
软件：Trojan-Qt5-Linux.AppImage 0.0.3
操作过程：正常连接一个节点，上网都正常，断开节点更换其他节点时出闪退。
Terminal图口提示
"There is some thing listening on port 1080 or 1081"
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by TheWanderingCoel** [comment]
看起来是端口并没有被释放掉然后再次连接了,privoxy太神奇了。

**Comment by TheWanderingCoel** [comment]
我记得我已经修复了啊，怎么没用...
