### ISSUE TITLE
Pac模式无效

### ISSUE THREAD

**Issue by dr1llc4t** [TheWanderingCoel/Trojan-Qt5#32]
0.03 版本Pac模式无法访问Google等网站，只能访问墙内的。关掉Pac就可以访问了
系统版本：macOS Catalina 10.15.3
浏览器版本：Safari 13.0.5（chrome也测试了，无效）

**Comment by TheWanderingCoel** [comment]
Windows么？windows不支持socks5,我稍后研究下。

**Comment by dr1llc4t** [comment]
> Windows么？windows不支持socks5,我稍后研究下。

抱歉，是Mac版本，我看看能不能贴一下log什么的

**Comment by TheWanderingCoel** [comment]
嗯，我这里测试没有问题。
![Screen Shot 2020-02-21 at 11 40 09 PM](https://user-images.githubusercontent.com/39617891/75048503-8ef67200-5503-11ea-82e8-97f2fe09ac89.png)

**Comment by dr1llc4t** [comment]
> 嗯，我这里测试没有问题。
> ![Screen Shot 2020-02-21 at 11 40 09 PM](https://user-images.githubusercontent.com/39617891/75048503-8ef67200-5503-11ea-82e8-97f2fe09ac89.png)

我刚才又测试了一遍，还是不行。log里也看不出什么问题，下面贴出来了

<img width="1049" alt="截屏2020-02-2123 49 03" src="https://user-images.githubusercontent.com/23226773/75049347-011b8680-5505-11ea-8a06-b3b30f52de92.png">
<img width="1038" alt="截屏2020-02-2123 49 50" src="https://user-images.githubusercontent.com/23226773/75049360-0547a400-5505-11ea-83da-71dedad55ffb.png">

[trojan.log.zip](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4236837/trojan.log.zip)

**Comment by TheWanderingCoel** [comment]
日志上的确看不出来，可否关了小飞机，同时开启enable pac测试下？顺便看一下system preferences的pac设置是否正确

**Comment by TheWanderingCoel** [comment]
pac文件的处理貌似有点问题，一直是1080端口

**Comment by dr1llc4t** [comment]
> 件的处理貌似有点问题，一直是

我重新捋了捋，刚才确实是小飞机影响。我这边Chrome测试可以了，但是Safari还是不行。另外，我这边打开软件不会自动连上节点，而且每次都会弹出是否接受网络连接。

**Comment by TheWanderingCoel** [comment]
还是有点多的，我测试下safari

**Comment by TheWanderingCoel** [comment]
的确,safari不行，我有空看下为啥

**Comment by dr1llc4t** [comment]
> 的确,safari不行，我有空看下为啥

辛苦了

**Comment by TheWanderingCoel** [comment]
找到原因了，马上push一个commit修复
