### ISSUE TITLE
客户端连接节点闪退

### ISSUE THREAD

**Issue by wjyue2001** [TheWanderingCoel/Trojan-Qt5#33]
系统：Windows 10 1909
软件：Trojan-Qt5 0.0.3
放在含中文的目录里，点击连接程序会闪退。最后放在磁盘根目录里解决

**Comment by TheWanderingCoel** [comment]
> 放在含中文的目录里，点击连接程序会闪退。最后放在磁盘根目录里解决

中文目录这个的确没处理好，我研究下。

**Comment by TheWanderingCoel** [comment]
是``QString``转``std::string``的问题，在修复。
