### ISSUE TITLE
客户端连接后闪断

### ISSUE THREAD

**Issue by LeslieSong** [TheWanderingCoel/Trojan-Qt5#34]
添加的服务器可以进行连接测试延迟，但是一点连接，就提示“已断开”
使用的 003最新版，放在根目录下也没用

**Comment by TheWanderingCoel** [comment]
能否看下日志？

**Comment by LeslieSong** [comment]
> 能否看下日志？

2020-02-22 10:32:09.924 ERROR [5044] [Logger::error@47] There is some thing listening on port 1080 or 1081
我把shadowsocks客户端退出后，在CMD里面已经查不到1080、1081端口占用了

**Comment by TheWanderingCoel** [comment]
能否试下重启？不确定是不是软件的判断问题。因为检测到端口占用就不会启动服务器

**Comment by LeslieSong** [comment]
> 能否试下重启？不确定是不是软件的判断问题。因为检测到端口占用就不会启动服务器

我把ss的自启动关了重启电脑试试

**Comment by LeslieSong** [comment]
> 能否试下重启？不确定是不是软件的判断问题。因为检测到端口占用就不会启动服务器

关了ss的自启，开机cmd查询确认无1080、1081端口占用后，启动客户端连接服务，还是报这个错……

**Comment by wjyue2001** [comment]
刚刚也出现同样的状况，重启一遍就好了，你试试

**Comment by LeslieSong** [comment]
> 刚刚也出现同样的状况，重启一遍就好了，你试试

重启应用还是重启程序？我重启过了还不行……

**Comment by wjyue2001** [comment]
重启计算机

**Comment by TheWanderingCoel** [comment]
我加个选项禁止检查端口吧

**Comment by TheWanderingCoel** [comment]
请尝试``v0.0.3 Bug Fix``

**Comment by TuT-Duval** [comment]
我的也是同样问题但是日志上是这样的：
2020-02-22 17:02:33.985 WARN  [16892] [Logger::warning@38] An instance of trojan-qt5 is already running

**Comment by TheWanderingCoel** [comment]
> 我的也是同样问题但是日志上是这样的：
> 2020-02-22 17:02:33.985 WARN [16892] [Logger::warning@38] An instance of trojan-qt5 is already running

已经有一个ss-qt5在运行了，尝试关掉再开

**Comment by LeslieSong** [comment]
> 请尝试`v0.0.3 Bug Fix`

谢谢，我试试！其实我已经曲线救国了，把端口改成了10800,10801，浏览器omega代理端口也改了10800。

**Comment by LeslieSong** [comment]
> 请尝试`v0.0.3 Bug Fix`

新版本可以了，感谢！
另外提个建议，如果更换服务器，直接默认断开之前的，连接新的。现在还要多做一步断开连接

**Comment by TheWanderingCoel** [comment]
这个主要是因为有需求多服务器，所以不敢这样
