### ISSUE TITLE
发现几点问题

### ISSUE THREAD

**Issue by MatthewDevelop** [TheWanderingCoel/Trojan-Qt5#37]
1.深色模式下，图标按钮状态非常不明显
2.能否自定义pac规则
3.流量统计目前好像没用

**Comment by TheWanderingCoel** [comment]
一的话其实还挺明显的
![Uploading Screen Shot 2020-02-22 at 1.00.26 PM.png…]()
![Screen Shot 2020-02-22 at 1 01 01 PM](https://user-images.githubusercontent.com/39617891/75086817-61491180-5573-11ea-98d1-fec529d76afe.png)
二的话在以后的版本中会加
三的话需要研究下trojan核心

**Comment by MatthewDevelop** [comment]
![image](https://user-images.githubusercontent.com/23044942/75086865-f3e9b080-5573-11ea-985f-685f01f8f77a.png)
我说的是这个地方呢！

**Comment by TheWanderingCoel** [comment]
这个啊，图标沿用的是``ss-qt5``的，等有没有UI大佬pr吧哎

**Comment by hellomrbigshot** [comment]
请问这是默认pac模式连接的吗，没有找到pac设置的选项

**Comment by TheWanderingCoel** [comment]
嗯，在设置，通用设置里

**Comment by GeraltShi** [comment]
mac平台
歪楼提个UI方面小建议，现在程序是常驻dock，能否做成只常驻在标题栏
以及通过dock/标题栏唤醒主面板的逻辑好像还不是很自然，点击dock主面板不弹出

**Comment by TheWanderingCoel** [comment]
> 以及通过dock/标题栏唤醒主面板的逻辑好像还不是很自然，点击dock主面板不弹出

好的，有空完成这个。实现起来并不难。

**Comment by TheWanderingCoel** [comment]
> mac平台

已经实现了，等下一个commit和别的feature一起提交
