### ISSUE TITLE
003版win10无法运行

### ISSUE THREAD

**Issue by TheRiceIsTooSalty** [TheWanderingCoel/Trojan-Qt5#39]
003版放入根目录，目录无中文，关闭安全软件，普通或管理员模式运行均无法正常显示软件，任务管理器可以看到稍纵即逝的程序……下载了002版可以运行，可添加节点，但连接后随即闪退……这可如何是好TT

**Comment by TheWanderingCoel** [comment]
0.0.3版有没有什么报错之类的？尝试在命令行下执行看看

**Comment by TheRiceIsTooSalty** [comment]
没有报错，根本没有显示，命令执行也是鼠标转个圈圈啥都没了，我在想是不是电脑里有什么软件冲突

**Comment by TheWanderingCoel** [comment]
这个还真的不清楚...

**Comment by TheRiceIsTooSalty** [comment]
神奇的情况😂没关系我等下一版吧 辛苦啦

**Comment by TheWanderingCoel** [comment]
我提交了一个v0.0.3的bug修复版，过会可以试下

**Comment by paopao88186** [comment]
> 我提交了一个v0.0.3的bug修复版，过会可以试下

为何我无法打开GOOGLE与youtube等网站?但steam和ins正常。

**Comment by TheWanderingCoel** [comment]
> 为何我无法打开GOOGLE与youtube等网站?但steam和ins正常。

关闭pac模式试试？

**Comment by paopao88186** [comment]
> > 为何我无法打开GOOGLE与youtube等网站?但steam和ins正常。
> 
> 关闭pac模式试试？

无效。
