### ISSUE TITLE
It is unclear how Trojan-Qt5 works on Mac

### ISSUE THREAD

**Issue by yjiangnan** [TheWanderingCoel/Trojan-Qt5#4]
There is no documentation.

From the Connection Manager menu, I click File and see options asking for "gui-config.json". What is that? Apparently, the imported file should have exactly the same name as spelled above. Is it the file containing all the configurations after one export it?

So, I tried "Connection --> Add". But again, it showed options I have no idea what they mean. I tried "From config.json" to load a file I have:
```
{
  "run_type": "client",
  "local_addr": "127.0.0.1",
  "local_port": 1080,
  "remote_addr": "11.22.33.44",
  "remote_port": 443,
  "password": ["DoNotForget8964"],
  "log_level": 1,
  "ssl": {
    "verify": true,
    "verify_hostname": true,
    "cert": "",
    "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
    "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
    "sni": "mydomain.com",
    "alpn": ["h2", "http/1.1"],
    "reuse_session": true,
    "session_ticket": false,
    "curves": ""
  },
  "tcp": {
    "no_delay": true,
    "keep_alive": true,
    "reuse_port": false,
    "fast_open": true,
    "fast_open_qlen": 20
  }
}

```
However, only a window "Profile Editor" pops up, with NO information from the config.json file loaded. After I manually input the information, it claims to be connected to my server on the other side of the Earth with a latency of only a few millisecond (which is impossible because of the limit of the speed of light). The system socks5 port 1080 is enabled in system Network Preferences, but Safari cannot connect to the Internet. I am not sure what is going wrong.

**Comment by TheWanderingCoel** [comment]
Hi, you can read the ``confighelper.cpp`` part about config. Anything except address, port, password, are fixed written in code. The latency part will request through the system proxy, ``1ms`` is expected when connected to the proxy.

**Comment by TheWanderingCoel** [comment]
Please make sure not to send the server information out, always use ``*`` to hide it.

**Comment by TheWanderingCoel** [comment]
Hope this photo can give you a clear view of the configuration, anything expect these are default values. Each time you click ``Connect``, a new ``config.json`` is generated based on the information in the Profile Editor. If you have some specific values you want to set in Profile Editor, feel free to say so. I will add it in next commit.
![QQ截图20200213235325](https://user-images.githubusercontent.com/39617891/74452818-8a570b80-4ebc-11ea-9db6-9d6749ff073d.png)

**Comment by yjiangnan** [comment]
Thanks for the reply. 
Should the `remote_addr` be remote server IP address or domain, or both are OK? Is it OK to just leave `sni` empty?

**Comment by TheWanderingCoel** [comment]
> remote_addr

I use domain. Better to use domain because your ssl certificate is based on domain. For ``sin`` you may check ``trojan`` official wiki. I think you can leave it empty. I always leave it empty.

**Comment by TheWanderingCoel** [comment]
Please also check [this](https://trojan-gfw.github.io/trojan/config). Closed as finished for now, if you have any issue, feel free to reopen it / open a new one.
