### ISSUE TITLE
怎么设置全局代理？

### ISSUE THREAD

**Issue by wingmancn** [TheWanderingCoel/Trojan-Qt5#40]
怎么设置全局代理？

希望在软件工具栏添加快捷的“全局代理”按钮

或者像以前SS那样直接桌面右下角图标上右键点击就能选择，这样最方便

**Comment by TheWanderingCoel** [comment]
在设置里可以设置。启动服务器就会设置，除非取消设置

**Comment by wingmancn** [comment]
win10，设置之后没反应，IE还是翻不了墙

**Comment by wingmancn** [comment]
现在只能用chrome

**Comment by TheWanderingCoel** [comment]
尝试下关闭PAC模式，PAC模式的问题将在0.0.4进行修复

**Comment by wingmancn** [comment]
谢谢，现在OK了，看来是要关闭PAC，而且要断开连接重连一次

**Comment by TheWanderingCoel** [comment]
试试0.0.3 Bug Fix版本,pac应该没有问题了。(得先删除pac文件夹）

**Comment by yiranyyu** [comment]
macOS 10.15.3，程序版本 0.0.3 Bug Fix released in 22-02-2020

**Comment by yiranyyu** [comment]
macOS 10.15.3，程序版本 0.0.3 Bug Fix released in 22-02-2020。
关闭 PAC 选项之后还是没有开启全局代理

**Comment by TheWanderingCoel** [comment]
第一个设置is auto set system proxy开启，重连服务器即可。我也是10.15.3

**Comment by yiranyyu** [comment]
> 第一个设置is auto set system proxy开启，重连服务器即可。我也是10.15.3

还是无法实现🙈。我在 General Settings 中仅开启第一项 【Auto set system proxy】，然后断开并重新连接或者重启 Trojan 然后重新连接都无法实现全局代理。如果是个例的话，可能是 MacOS 的问题吧 orz

（需要的话我可以邮件一份录屏）

**Comment by TheWanderingCoel** [comment]
系统设置中代理有没有被设置上？
![image](https://user-images.githubusercontent.com/39617891/75152185-6f4d8c80-5743-11ea-8e5d-6b8752467ce5.png)

**Comment by yiranyyu** [comment]
> 系统设置中代理有没有被设置上？
> ![image](https://user-images.githubusercontent.com/39617891/75152185-6f4d8c80-5743-11ea-8e5d-6b8752467ce5.png)

没有，我以为是和 ShadowsocksX-NG 一样可以仅通过应用程序的设置来更改。之前使用 ShadowsocksX-NG 时不需要修改系统设置中的代理选项。

钩上系统代理之后是可以实现全局代理，而且不需要开启【Auto set system proxy】选项就可以实现全局代理。

感觉如果能在程序设置中直接完成开关会更方便，类似于 shadowsocks 客户端的效果，建议能够加上。非常感谢作者提供的客户端，目前已经很可用了！

**Comment by TheWanderingCoel** [comment]
emmm...有点尴尬，因为[auto set system proxy]就是设置系统偏好设置的代理。可能遇到了什么bug设置不上。

**Comment by yiranyyu** [comment]
> emmm...有点尴尬，因为[auto set system proxy]就是设置系统偏好设置的代理。可能遇到了什么bug设置不上。

我查了一下发现确实自动设置了 Wi-Fi 的代理，不过我用的是网线所以才出了问题（并没有自动设置 USB 10/100/1000 LAN 的代理选项）。可能确实是个 bug。
![image](https://user-images.githubusercontent.com/28106858/75153755-226bb500-5747-11ea-80c4-4423960ad2e4.png)

**Comment by TheWanderingCoel** [comment]
这个的确没考虑到，因为怕所有都给设置一遍容易让程序短暂卡住，只设置了Aiport,Ethernet和Wi-Fi这三个

**Comment by TheWanderingCoel** [comment]
已修复
