### ISSUE TITLE
003版本 mac os仍旧无法联网

### ISSUE THREAD

**Issue by meowuuu** [TheWanderingCoel/Trojan-Qt5#41]
003版本 mac os仍旧无法联网
mac os 10.14.6

**Comment by meowuuu** [comment]
<img width="440" alt="1" src="https://user-images.githubusercontent.com/5517298/75088232-57300e80-5585-11ea-9625-739df6b1d54b.png">

**Comment by TheWanderingCoel** [comment]
请打码先

**Comment by meowuuu** [comment]
<img width="440" alt="1" src="https://user-images.githubusercontent.com/5517298/75088286-0c62c680-5586-11ea-82ce-58185cd2acfb.png">

**Comment by TheWanderingCoel** [comment]
检查下系统代理设置是不是设置成了无效的代理，检查下路由表和服务器连通性/端口是否开放

**Comment by meowuuu** [comment]
应该不是的，昨天还是可以联网的，今天就不行了

**Comment by TheWanderingCoel** [comment]
有可能是服务器问题，我这里catalina 10.15.3没有问题

**Comment by pb2n** [comment]
我三台macos  两台是正常的 一台和你一样 昨天还能用今天开机就玄学失灵了

**Comment by meowuuu** [comment]
![image](https://user-images.githubusercontent.com/5517298/75088401-9f503080-5587-11ea-9d01-59b461700697.png)

**Comment by meowuuu** [comment]
个别看着有速度的服务器，点连接就成这样了

**Comment by pb2n** [comment]
那个服务器配置文件是在哪个文件夹的呀 清空了重新试试

**Comment by meowuuu** [comment]
不用删文件夹，客户端可以删掉列表。怎么感觉是从客户端层面禁用了，被黑名单了？

**Comment by TheWanderingCoel** [comment]
在``~/.config/trojan-qt5``里

**Comment by TheWanderingCoel** [comment]
> 不用删文件夹，客户端可以删掉列表。怎么感觉是从客户端层面禁用了，被黑名单了？
客户端没有任何黑名单，很有可能出现了bug。

**Comment by TheWanderingCoel** [comment]
能否提供下日志？

**Comment by meowuuu** [comment]
> > 不用删文件夹，客户端可以删掉列表。怎么感觉是从客户端层面禁用了，被黑名单了？
> 
> 客户端没有任何黑名单，很有可能出现了bug。



> 能否提供下日志？

如何操作？

**Comment by TheWanderingCoel** [comment]
> > > 不用删文件夹，客户端可以删掉列表。怎么感觉是从客户端层面禁用了，被黑名单了？
> > 
> > 
> > 客户端没有任何黑名单，很有可能出现了bug。
> 
> > 能否提供下日志？
> 
> 如何操作？

Help->Trojan Log, Help->Gui Log

**Comment by meowuuu** [comment]
[gui_log.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4238952/gui_log.txt)
trojan log空

**Comment by pb2n** [comment]
2020-02-22 13:49:36.673 ERROR [4177] [Logger::error@47] There is some thing listening on port 1080 or 1081

**Comment by TheWanderingCoel** [comment]
端口被占用，检查下端口

**Comment by meowuuu** [comment]
原来是V2ray自动启动把端口占了，好了
