### ISSUE TITLE
enhancement request: 批量添加多个uri功能

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#42]
当前添加uri是通过trojan：// ,窗口只适合单个地址添加，无法批量，参考passwall可以在web上批量添加几十个节点，希望大佬也可以考虑下实现此功能

**Comment by TheWanderingCoel** [comment]
通过什么进行分割呢，``\n``还是``\r\n``

**Comment by babylife** [comment]
这个把我问倒了 ，是否可以换行的方式实现呢？即一行一个地址,比如下面的样子。抱歉我非开发人员可能无法理解换行和回车，不过用户需求始终是简单化的。 

还有个想法是不是是自动搜索trojan到443结尾的正则表达。然后自动完整匹配 

trojan://DKSx3TSDssssss:443
trojan://DKSx3TSDssssss:443
trojan://DKSx3TSDssssss:443
trojan://DKSx3TSDssssss:443
trojan://DKSx3TSDssssss:443
trojan://DKSx3TSDssssss:443
trojan://DKSx3TSDssssss:443

**Comment by TheWanderingCoel** [comment]
https://github.com/trojan-gfw/trojan-url/blob/master/README.md
这个是trojan官方的url格式，因为这个程序扩展了一下url scheme,#后面代表的是服务器名称，我可能会采用\n进行分割。并且不一定兼容别的服务提供商

**Comment by babylife** [comment]
好的，谢谢
