### ISSUE TITLE
请问如何自定义user.txt合并实现默认的gfw的pac文件

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#43]
当前看到pac目录有一文件，不知道是否会自动更新，是否可以和本地的自定义user.txt 实现合并？

**Comment by TheWanderingCoel** [comment]
自定义``pac``没有暂时实现。

**Comment by babylife** [comment]
好的，谢谢老大。 请问是否可以手动修改该pac文件，会不会被自动更新给覆盖？

**Comment by TheWanderingCoel** [comment]
启动服务器就会被自动覆盖

**Comment by QierLi** [comment]
期待自定义pac功能，谢谢你的工作！

> 自定义`pac`没有暂时实现。
