### ISSUE TITLE
MacOS客户端连接闪退

### ISSUE THREAD

**Issue by VEI7** [TheWanderingCoel/Trojan-Qt5#52]
点击连接程序意外退出，1080和1081没有被占用。报错如下：

**Comment by TheWanderingCoel** [comment]
看日志是``boost::wrapexceptboost::property_tree::json_parser::json_parser_error: /Users/jiaqiwei/.config/trojan-qt5/config.json: cannot open file``并没有生成config.json文件，服务器配置有问题？

**Comment by VEI7** [comment]
需要怎么配置呢

**Comment by TheWanderingCoel** [comment]
请将profile editor中的配置截图发一下（请千万要打码服务器地址和密码）

**Comment by VEI7** [comment]
![1651582386749_ pic_hd](https://user-images.githubusercontent.com/32030584/75095314-7010e200-55ce-11ea-8909-ea7f66f9ef35.jpg)

**Comment by TheWanderingCoel** [comment]
密码有没有特殊字符？

**Comment by VEI7** [comment]
这个密码是我的账户密码吗？如果是的话没有特殊字符。profile editor里的这个密码是隐藏的，看不到，但是位数与我的账户密码位数不一致

**Comment by TheWanderingCoel** [comment]
账户密码？用的是机场么？

**Comment by VEI7** [comment]
shadowsocks

**Comment by TheWanderingCoel** [comment]
这个是trojan的客户端不是shadowsocks的啊...

**Comment by VEI7** [comment]
shadowsocks这两天上线了新协议（Trojan）节点，我再问问shadowsocks的客服吧。感谢！

**Comment by TheWanderingCoel** [comment]
shadowsocks机场啊...那有可能是是我客户端有bug

**Comment by coderstory** [comment]
我用的是那个服务商的服务器 没问题 之前给他们发工单 推荐Trojan-Qt5的

**Comment by VEI7** [comment]
你好，能判断出我这个问题是什么原因吗？现在还是没搞定，别人用那个服务商的配置好像没有问题，我也不清楚是不是我哪步出错了

**Comment by TheWanderingCoel** [comment]
能否进下这个目录看一下``/Users/jiaqiwei/.config/trojan-qt5/``?怀疑是不是权限问题。

**Comment by VEI7** [comment]
没有这个目录
localhost:~ jiaqiwei$ sudo cd /Users/jiaqiwei/.config/trojan-qt5/
/usr/bin/cd: line 4: cd: /Users/jiaqiwei/.config/trojan-qt5/: No such file or directory
localhost:~ jiaqiwei$ sudo ls /Users/jiaqiwei/.config/
configstore

**Comment by VEI7** [comment]
没有这个目录
localhost:~ jiaqiwei$ sudo cd /Users/jiaqiwei/.config/trojan-qt5/
/usr/bin/cd: line 4: cd: /Users/jiaqiwei/.config/trojan-qt5/: No such file or directory
localhost:~ jiaqiwei$ sudo ls /Users/jiaqiwei/.config/
configstore

**Comment by TheWanderingCoel** [comment]
看样子问题在这。创建不了这个文件目录.....
试试``sudo chown -R jiaqiwei  /Users/jiaqiwei/.config/``
``sudo chmod -R 755  /Users/jiaqiwei/.config/``

**Comment by VEI7** [comment]
确实是这个问题，解决了，感谢

**Comment by TheWanderingCoel** [comment]
没事，解决了就好。
