### ISSUE TITLE
[Feature request] Hoping for subscription support

### ISSUE THREAD

**Issue by sino1641** [TheWanderingCoel/Trojan-Qt5#53]
I am a normal user of ur app on windows.
My`airport` has a lot of nodes for trojan but I have to import them manually.
So I wonder if you could support batch-import by subscription link, thx!
AFAIK, `Shadowrocket` and `Pharos` on mobile platforms have this function, hoping it is helpful for ur development.

**Comment by TheWanderingCoel** [comment]
Can you tell me the line separator? I haven't seen many trojan airport.

**Comment by sino1641** [comment]
So sorry that I don't know what do u mean `line separator` as I have ZERO programming experience:pensive:
But I notice that qt has a built-in base64 decoding function called [QByteArray](https://doc.qt.io/qt-5/qbytearray.html) and it seems to work.
Here is an example for u:
`dHJvamFuOi8vcGFzc3dvcmQxQGhvc3Q6cG9ydDEjTmFtZTENCnRyb2phbjovL3Bhc3N3b3JkMkBob3N0OnBvcnQyI05hbWUyDQo=`
which should be decoded as 

> trojan://password1@host:port1#Name1
> trojan://password2@host:port2#Name2

The URI format is the same as ur client~

**Comment by TheWanderingCoel** [comment]
Sure. I will do some research about that and add it in v0.0.4

**Comment by TheWanderingCoel** [comment]
I see. The linke separator is ``\r\n``

**Comment by sino1641** [comment]
Hi, dev
I can't see where to add my subscription link on 0.0.4:cry:

**Comment by TheWanderingCoel** [comment]
I only added batch import uri link. You can manually access the link to get trojan:// uris. Subscription link requires a manager which will be added in v0.0.5

**Comment by TheWanderingCoel** [comment]
> Hi, dev
> I can't see where to add my subscription link on 0.0.4😢

Finally supported in ``v0.0.4b`

**Comment by sino1641** [comment]
I still can not see where to add subscription links in` 0.0.4c` :cry:
![](https://i.loli.net/2020/03/17/7vqix3M2XZgHY5z.png)

**Comment by TheWanderingCoel** [comment]
> I still can not see where to add subscription links in` 0.0.4c` 😢
> ![](https://camo.githubusercontent.com/e8e2ab1682808f77fbdf864a9c5d3760360cde09/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30332f31372f3776716978334d32585a674859357a2e706e67)

It's in systemTray. Right Click, Server Subscription

**Comment by sino1641** [comment]
It seems that the` link separator `didn't separated :sob:
![](https://i.loli.net/2020/03/17/8NYKV4J7z3oUebE.png)

**Comment by TheWanderingCoel** [comment]
Akward... Maybe I shoud purchase an airport with trojan subscription for testing...

**Comment by sino1641** [comment]
Finally added and functioned normally in `v0.0.5`
Thanks for your work! @TheWanderingCoel

**Comment by TheWanderingCoel** [comment]
@sino1641 You're more than welcome~
