### ISSUE TITLE
[Refinement Request] Minor Refinements Required.

### ISSUE THREAD

**Issue by DonghanLyu** [TheWanderingCoel/Trojan-Qt5#56]
First of all, many thanks to @TheWanderingCoel 's great work. This software helps everyone who used it to break the barriers the GFW made.

And after a few days of experience, I'd like to make a request for some extra features on macOS in foreseeable future.

1. Keyboard combinations: In most circumstances, both built-in and 3rd-party softwares on macOS use ⌘ + , (Command + Comma) to open General Settings page. So, if I may, I'd like to gently ask the developer to add this feature.

2. One-Time Click: I set up multiple ports in Trojan. Sometimes one may be unstable and inaccessible, so I'll switch to other ports. But when I clicked a new proxy, I cannot quickly connect to it, and the former proxy was still on. So, please add a new feature that allows users to quickly connect to new server and auto-disconnect the former one.

3. Last-Used Port Auto-Location: Each time I re-open Trojan, I have to scroll down and find my server. It would be a great delight to me if Trojan supports last-used auto-location feature.

4. Simplify Columns: There're lots of info and these columns can't be shown in one page. So please simplify these columns and move some of them into Status bar pop-up menu.

Again, thanks for your app and your time. Have a nice day! ;-)

**Comment by TheWanderingCoel** [comment]
Hi there, You're more than welcome.

I'd like to make a short response to those features.

1) This can be easily done. I will add it in next few commits.
2) This can also be easily done. I will add a settings to allow connect only server at the same time.
3) You can sort the server by last used time, this is not a big issue.
4) I will do it in the next few commits.

Thank you and everyone who support this project, have a fantastic weekend. :)

**Comment by DonghanLyu** [comment]
Thank you for your quick response. 👏🏻

**Comment by DonghanLyu** [comment]
New updates:

5. Emoji Support: From my personal point of view, I'd prefer images than words. And please add support in further upgrades for Emoji support.

6. Sequence Optimizing: Under version 0.0.3 (bug fix), the sequence of Chinese characters is messed up, e.g. 东(Dōng)京 is on the top of the list, while 爱(Ài)沙尼亚 is in the middle of the list.

7. QR Code Capture: I have authorized Trojan to record my screen, but built-in QR Code Capturer is not available. Neither is the feature: "Scan QR Code on Screen".

8. (MAYBE) IPv6: I suppose your app successfully supports for IPv6 network. If so, please ignore this. If not, please add support for IPv6.

**Comment by DonghanLyu** [comment]
New updates:

5. Emoji Support: From my personal point of view, I'd prefer images than words. And please add support in further upgrades for Emoji support.

6. Sequence Optimizing: Under version 0.0.3 (bug fix), the sequence of Chinese characters is messed up, e.g. 东京 is on the top of the list, while 爱沙尼亚 is in the middle of the list.

7. QR Code Capture: I have authorized Trojan to record my screen, but built-in QR Code Capturer is not available. Neither is the feature: "Scan QR Code on Screen".

8. (MAYBE) IPv6: I suppose your app successfully supports for IPv6 network. If so, please ignore this. If not, please add support for IPv6.

**Comment by TheWanderingCoel** [comment]
Hi. I will consider these new features, however it take times. I have now 38 issues to close....

**Comment by DonghanLyu** [comment]
Take your time! Thank you anyway, just maybe when you are free, take these suggestions into account. 😃

**Comment by TheWanderingCoel** [comment]
I will haha. Thank you for making so many good suggestions! :D
