### ISSUE TITLE
mac系统10.11.5提示需要10.12，请问除了升级OS X还有其他办法吗？

### ISSUE THREAD

**Issue by llwinner** [TheWanderingCoel/Trojan-Qt5#57]
mac系统10.11.5提示需要10.12，请问除了升级OS X还有其他办法吗？升级系统的话，老机器带不起来。。。

**Comment by TheWanderingCoel** [comment]
诶...这个因为老系统几乎不咋用。默认好像就是10.12版本。我尝试打包一个10.11版本的看看吧

**Comment by TheWanderingCoel** [comment]
因为很多依赖的问题，很可能带不起来的...

**Comment by llwinner** [comment]
非常感谢如此迅速的回复，千万别因为我这个问题浪费太多时间，我估计过段时间也要换新电脑了，我先用命令行端就可以 ^_^

**Comment by TheWanderingCoel** [comment]
> 非常感谢如此迅速的回复，千万别因为我这个问题浪费太多时间，我估计过段时间也要换新电脑了，我先用命令行端就可以 ^_^
感谢支持~我有空研究一下
