### ISSUE TITLE
win10下0.0.3, 0.0.4 均崩溃。

### ISSUE THREAD

**Issue by MMaxwell66** [TheWanderingCoel/Trojan-Qt5#58]
0.0.2可用。
可靠性报告如下：

> 源
> trojan-qt5
> 
> 摘要
> 已停止工作
> 
> 日期
> ‎2020/‎2/‎22 22:23
> 
> 状态
> 已发送报告
> 
> 描述
> 错误的应用程序路径:	D:\Files\Trojan\0.0.3\trojan-qt5.exe
> 
> 问题签名
> 问题事件名称:	BEX
> 应用程序名:	trojan-qt5.exe
> 应用程序版本:	0.0.0.0
> 应用程序时间戳:	5e4fe705
> 故障模块名称:	ucrtbase.dll
> 故障模块版本:	10.0.18362.387
> 故障模块时间戳:	6dbf7eae
> 异常偏移:	0009e6eb
> 异常代码:	c0000409
> 异常数据:	00000007
> OS 版本:	10.0.18363.2.0.0.768.99
> 区域设置 ID:	2052
> 其他信息 1:	4439
> 其他信息 2:	4439781cca8c29b60c0b4c1d3936e10d
> 其他信息 3:	6c60
> 其他信息 4:	6c60f4028b13705f47a246e0ca02aeac
> 
> 关于该问题的额外信息
> 存储段 ID:	064bb980863930c49566caf1fda4a091 (1542143063112327313)
>

**Comment by TheWanderingCoel** [comment]
我这里没有遇到过诶，需要研究下。具体执行了什么操作呢？

**Comment by MMaxwell66** [comment]
就双击运行后，在任务管理器出现了一会就没了。翻可靠性报告有上面的记录。

**Comment by TheWanderingCoel** [comment]
在Windows 10 1909 Update Dec 2019上测试了一下，没有发现上述情况。看上去是``ucrtbase.dll``，VC运行库造成的？可否更新下运行库并尝试下这个链接的操作？http://www.winwin7.com/JC/16616.html

**Comment by MMaxwell66** [comment]
系统版本1909的18363.657。试了链接里的，还是一样的错误。

**Comment by TheWanderingCoel** [comment]
重启试试？

**Comment by MMaxwell66** [comment]
也试了，并没用。

**Comment by TheWanderingCoel** [comment]
麻烦只能0.0.2先用着了，可能需要研究好久这个问题

**Comment by MMaxwell66** [comment]
没事，0.0.2用着也ok，就是没有pac有点麻烦。

**Comment by PandaCircle** [comment]
win10 1903 运行会提示应用程序无法正常启动

**Comment by TheWanderingCoel** [comment]
错误代码是什么？

**Comment by xutaoqw** [comment]
我和楼主一模一样的问题，0.0.3和0.0.4都打不开  0.0.2能打开

**Comment by TheWanderingCoel** [comment]
系统是32位的吗

**Comment by ZhangJiangYong-ccc** [comment]
一样的问题，连0.0.2都闪退。。。

**Comment by TheWanderingCoel** [comment]
如果用命令行运行trojan-qt5.exe有什么输出吗

**Comment by MMaxwell66** [comment]
64系统。命令行运行没有输出，返回值好像是9的样子。

**Comment by TheWanderingCoel** [comment]
挺棘手的...

**Comment by TheRiceIsTooSalty** [comment]
看了下我也是这个情况 网上找了几个所谓的修复办法还是没用😭😭😭

**Comment by TheWanderingCoel** [comment]
大家都是这个问题吗...我这里没法复现真的很难办...对不起各位

**Comment by PandaCircle** [comment]
> 错误代码是什么？

0xc000007b ，感觉是dll的问题？

**Comment by TheWanderingCoel** [comment]
> > 错误代码是什么？
> 
> 0xc000007b ，感觉是dll的问题？
> 同一版本的win10 ，另一台机就没问题

对，这种情况随机的。。。也不好排查。感觉跟VC运行库有关系？

**Comment by MMaxwell66** [comment]
我感觉还是有异常没处理，我装个qt看看能不能通过源码定位吧。

**Comment by MMaxwell66** [comment]
qt下载太麻烦了...已放弃。
我用VS看了下应该是0x75523db2处抛了个std::runtime没处理，不过这个地址应该是系统dll里的应该没啥帮助吧

**Comment by TheWanderingCoel** [comment]
qt的话有镜像站，其实不麻烦。装上msvc2017 32bit，编译qhttpserver，安装依赖应该就可以了

**Comment by dispassion79** [comment]
> 我这里没有遇到过诶，需要研究下。具体执行了什么操作呢？

同样的问题，我笔记本win10能运行最新的中文版，台式机打开后桌面没有任何显示。目前台式机能使用0.02版，每次连接成功后报一个privoxy Error的错误，显示can't check configuration file，但是不影响代理-_-||

**Comment by TheWanderingCoel** [comment]
privoxy error是英文路径有空格导致的错误，在0.0.3之后都修复了。不知道0.0.3版本为什么好多人都会崩溃...

**Comment by TheWanderingCoel** [comment]
https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/releases/download/v0.0.0/vc_redist.x86.exe
试试安装这个？

**Comment by DD-minelong** [comment]
> https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/releases/download/v0.0.0/vc_redist.x86.exe
> 试试安装这个？

安装完这个 0.0.3,0.0.4 依然崩溃... 还是用0.0.2版本中-。-

**Comment by TheWanderingCoel** [comment]
try ``0.0.4a``?

**Comment by MMaxwell66** [comment]
我这里是好了。

**Comment by TheWanderingCoel** [comment]
0.0.4a正常了吗？那就好，我也不知道啥原因。奇奇怪怪的

**Comment by MMaxwell66** [comment]
对的，更0.0.4a后可用。

**Comment by TheWanderingCoel** [comment]
那就好，原因也是莫名其妙的。先关了

**Comment by DD-minelong** [comment]
感谢！0.0.4a后正常

**Comment by TheWanderingCoel** [comment]
原因我至今也不知道。不管了，大家可以用了就行
