### ISSUE TITLE
cannot run with error message 

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#6]
![Snipaste_2020-02-18_10-04-28](https://user-images.githubusercontent.com/31977161/74697624-2888ff80-5236-11ea-8165-b680018a143d.png)

**Comment by babylife** [comment]
issue fixed after move to other location . seems the root cause is the file unc cannot include space

**Comment by TheWanderingCoel** [comment]
Might be the reason of privoxy itself. Maybe you could open an issue to privoxy?

**Comment by babylife** [comment]
yes. should be the issue of privoxy, i will raise a ticket for them.

**Comment by TheWanderingCoel** [comment]
I was thinking maybe it was due to the path? my way of starting privoxy on ```windows`` is command line. You can try head into ``privoxy`` dir. And try``privoxy.exe 'Your Config Path have Space'`` to check if it's the issue of privoxy.

**Comment by babylife** [comment]
yes, the path issue, since my username include the a space. actually the error message shows a wrong path already.
