### ISSUE TITLE
Mac连接有线网，无法上Google

### ISSUE THREAD

**Issue by GuanHenan** [TheWanderingCoel/Trojan-Qt5#61]
Mac连接同一节点，使用家用Wifi可以上Google，但是连接有线网无法上Google。
防火墙未打开。

**Comment by TheWanderingCoel** [comment]
检查系统代理设置，很可能没把有线网的设置上

**Comment by GuanHenan** [comment]
> 检查系统代理设置，很可能没把有线网的设置上

好的，已解决。方法：系统偏好设置-网络-选择自己使用的有线网络-高级-代理-选中自动代理配置。

**Comment by TheWanderingCoel** [comment]
好的。如果有问题可以重开issue
