### ISSUE TITLE
WIN10无法连接

### ISSUE THREAD

**Issue by geniusgk77** [TheWanderingCoel/Trojan-Qt5#62]
点击连接以后没有任何反应，还是现实未连接，但是有延时提示

**Comment by TheWanderingCoel** [comment]
日志有没有输出？

**Comment by geniusgk77** [comment]
有，好像是被原来的小飞机占用了，推掉好像就可以了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午3:27
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




日志有没有输出？

**Comment by TheWanderingCoel** [comment]
好的👌

**Comment by geniusgk77** [comment]
vimeo，连接不上，youtube可以


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午3:30
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




好的

**Comment by TheWanderingCoel** [comment]
试试关闭PAC?

**Comment by geniusgk77** [comment]
关闭了，还是连接不上


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午3:33
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




试试关闭PAC?

**Comment by TheWanderingCoel** [comment]
关闭后重新连接服务器试试？然后试试cli做一个对比，看看是不是服务器问题

**Comment by geniusgk77** [comment]
换了节点好像就可以了，有的节点不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午3:45
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




关闭后重新连接服务器试试？然后试试cli做一个对比，看看是不是服务器问题

**Comment by TheWanderingCoel** [comment]
那应该是服务器问题

**Comment by geniusgk77** [comment]
苹果手机的话要怎么操作呢，下载不到app




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: TheWanderingCoel <notifications@github.com&gt;
发送时间: 2020年2月23日 16:21
收件人: TheWanderingCoel/Trojan-Qt5 <Trojan-Qt5@noreply.github.com&gt;
抄送: geniusgk77 <64065337@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




那应该是服务器问题

**Comment by TheWanderingCoel** [comment]
> 苹果手机的话要怎么操作呢，下载不到app 发自我的iPhone

苹果可以下载Shadowrocket/ Pharos, 美区有。暂时没有时间写苹果app

**Comment by geniusgk77** [comment]
是的，我看到有，但是要付钱，没办法付钱


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上7:59
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)



 
苹果手机的话要怎么操作呢，下载不到app 发自我的iPhone
  
苹果可以下载Shadowrocket/ Pharos, 美区有。暂时没有时间写苹果app

**Comment by TheWanderingCoel** [comment]
可以找代购，这个的话你得自己研究了。。。我不知道谁可以代购

**Comment by geniusgk77** [comment]
好的
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上8:02
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




可以找代购，这个的话你得自己研究了。。。我不知道谁可以代购

**Comment by geniusgk77** [comment]
又连接不上了，很奇怪，之前都是好好的，显示连接了，但是没有用，什么都看不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheWanderingCoel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上8:02
收件人:&nbsp;"TheWanderingCoel/Trojan-Qt5"<Trojan-Qt5@noreply.github.com&gt;;
抄送:&nbsp;"NEW KING"<64065337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheWanderingCoel/Trojan-Qt5] WIN10无法连接 (#62)




可以找代购，这个的话你得自己研究了。。。我不知道谁可以代购

**Comment by TheWanderingCoel** [comment]
检查系统代理设置，pac，顺便切换服务器试试
