### ISSUE TITLE
中文本地化

### ISSUE THREAD

**Issue by bbbear2002** [TheWanderingCoel/Trojan-Qt5#68]
大概啥时候能增加本地化？

**Comment by TheWanderingCoel** [comment]
中文本地化在windows和linux是有的，详见``resources/i18n/``。macOS不知道为啥不会本地化

**Comment by sidoinefr** [comment]
我研究了半天，不知道怎样设置出mac os里这个app的中文，您有什么办法可以显示中文吗？既然win端可以实现中文本地化

**Comment by TheWanderingCoel** [comment]
> 我研究了半天，不知道怎样设置出mac os里这个app的中文，您有什么办法可以显示中文吗？既然win端可以实现中文本地化

照理来说是全平台的，mac os好像不知道为啥出bug了，并不会汉化。等有时间研究一下

**Comment by sidoinefr** [comment]
> > 我研究了半天，不知道怎样设置出mac os里这个app的中文，您有什么办法可以显示中文吗？既然win端可以实现中文本地化
> 
> 照理来说是全平台的，mac os好像不知道为啥出bug了，并不会汉化。等有时间研究一下

好的，谢谢您

**Comment by TheWanderingCoel** [comment]
v0.0.4修复

**Comment by sidoinefr** [comment]
> v0.0.4修复

真棒，期待！谢谢

**Comment by TheWanderingCoel** [comment]
已完成，请等待构建完成后尝试``v0.0.4``
