### ISSUE TITLE
启动PAC模式后，IDM要如何配置才能下载YOUTUBE？

### ISSUE THREAD

**Issue by andrewzchn** [TheWanderingCoel/Trojan-Qt5#69]
启动PAC模式后，IDM要如何配置才能下载YOUTUBE？

**Comment by TheWanderingCoel** [comment]
IDM我没用过，会不会自动跟随系统代理？

**Comment by coderstory** [comment]
idm 设置里 代理选项
设置成使用系统配置 或者手动127.0.0.1:8010

**Comment by EA-DICE** [comment]
> idm 设置里 代理选项
> 设置成使用系统配置 或者手动127.0.0.1:8010

我也遇到这个问题，但idm代理选项设置为使用系统配置后仍无法下载YouTube，可否具体说说如何解决？谢谢

**Comment by TheWanderingCoel** [comment]
> > idm 设置里 代理选项
> > 设置成使用系统配置 或者手动127.0.0.1:8010
> 
> 我也遇到这个问题，但idm代理选项设置为使用系统配置后仍无法下载YouTube，可否具体说说如何解决？谢谢

IDM支持http还是socks5？根据支持的协议填地址就好了

**Comment by EA-DICE** [comment]
> > > idm 设置里 代理选项
> > > 设置成使用系统配置 或者手动127.0.0.1:8010
> > 
> > 
> > 我也遇到这个问题，但idm代理选项设置为使用系统配置后仍无法下载YouTube，可否具体说说如何解决？谢谢
> 
> IDM支持http还是socks5？根据支持的协议填地址就好了

界面是这样的
![捕获](https://user-images.githubusercontent.com/42771283/75133555-3e0a9780-5716-11ea-9fae-6e9fc641fd27.PNG)

**Comment by TheWanderingCoel** [comment]
试试手动配置？地址127.0.0.1 端口你的socks5端口。对以下服务器使用代理选http,https

**Comment by EA-DICE** [comment]
> 试试手动配置？地址127.0.0.1 端口你的socks5端口。对以下服务器使用代理选http,https

用户名不太清楚要填什么，网络服务提供商没给

**Comment by TheWanderingCoel** [comment]
这个用户名和密码指的是本地socks5的，留空即可

**Comment by EA-DICE** [comment]
> 这个用户名和密码指的是本地socks5的，留空即可

好的，正在进行测试

**Comment by EA-DICE** [comment]
> 这个用户名和密码指的是本地socks5的，留空即可

经过测试，YouTube可以正常下载，谢谢悉心指导

**Comment by TheWanderingCoel** [comment]
没事，那我先关了这个issue

**Comment by EA-DICE** [comment]
> 没事，那我先关了这个issue

收到
