### ISSUE TITLE
the v2 is very good. one question is how to run with gfw mode?

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#7]
seems all trace go through via proxy. is there a way for gfw rule ?

**Comment by TheWanderingCoel** [comment]
you mean ``pac`` mode? I will add it next version. Thanks for suggestion?

**Comment by babylife** [comment]
Good news! yes pac mode.  thank you brother!

**Comment by TheWanderingCoel** [comment]
You're welcome.
