### ISSUE TITLE
我怎么就没找到0.0.4的版本

### ISSUE THREAD

**Issue by Yoodaa** [TheWanderingCoel/Trojan-Qt5#70]
这里的release没有
官网资源下载里面的那个文件名是对的，但是打开后看程序的about还是0.0.3
而且这两个版本都有导入配置无法保存和连接服务器崩溃的问题

**Comment by TheWanderingCoel** [comment]
大家一直说的0.0.4其实就是0.0.3 Bug Fix,导入配置需要点击文件->手动保存。连接服务器崩溃请检查路径是否包含了空间和中文

**Comment by Yoodaa** [comment]
哦，忘了说了，我是mac os 10.15.3，以上解决办法无效

**Comment by Yoodaa** [comment]
已自行解决
通过查看崩溃详细信息发现由于权限不足无法打开 ~/.config 目录
原来这个目录的所有者是root，改成当前用户的就可以了

**Comment by TheWanderingCoel** [comment]
好的感谢研究，我可能error handler做的不是很好。~/.config是root权限的情况的确少见。
