### ISSUE TITLE
为什么点击连接后，却不能连接上

### ISSUE THREAD

**Issue by ezzhong** [TheWanderingCoel/Trojan-Qt5#73]
测试服务器是有反应，也反馈了延迟时间，但是点击连接后，状态却没有显示为连接

而且尝试使用强制连接，也依然无法连接上，请问这是什么问题？
![click but not connect](https://user-images.githubusercontent.com/61397473/75124602-5618f180-56eb-11ea-93a9-dd8fc760e94a.JPG)

**Comment by ezzhong** [comment]
刚刚又测试了一下，发现是我自己的ss客户端没有关闭，发现关闭程序后可以了。

貌似是ss的客户端，即使不连接任何服务器，只要程序打开着也会影响Trojan的使用。

**Comment by llwinner** [comment]
快把服务器打码或者删除吧。

**Comment by ezzhong** [comment]
> 快把服务器打码或者删除吧。

好的，谢谢提醒

**Comment by TheWanderingCoel** [comment]
很有可能是ss的客户端监听了端口，虽然没有连接。服务器发出来一定要打码
