### ISSUE TITLE
win7 x64 使用trojain0.0.4版本，随机测试的部分节点都不能连接

### ISSUE THREAD

**Issue by feirpri** [TheWanderingCoel/Trojan-Qt5#74]
系统：win7 x64
版本: 0.0.4

在安卓手机上测试可用的节点，在windows上测试连接。可以显示延迟数据，但是连接不上

**Comment by TheWanderingCoel** [comment]
如果是通过trojan://导入的，请确认密码是否正确。请post出日志&尝试使用cli客户端进行连接。

**Comment by feirpri** [comment]
抱歉抱歉，我的问题。没有注意到shadowsocks在运行，导致端口被占用了

**Comment by TheWanderingCoel** [comment]
没事，我把这个tag成good first issue可以让也有这个问题的人看见。
