### ISSUE TITLE
建议添加监听 0.0.0.0 允许其他设备接入的功能

### ISSUE THREAD

**Issue by kevinfu2** [TheWanderingCoel/Trojan-Qt5#75]
建议添加监听 0.0.0.0 允许其他设备接入的功能

**Comment by TheWanderingCoel** [comment]
在配置编辑器将127.0.0.1改成0.0.0.0即可

**Comment by augustus2000** [comment]
配置成0.0.0.0不行，局域网的机器连不上这个代理，换成具体的ip倒是可以

**Comment by left3721** [comment]
Linux下没问题  把127.0.0.1 改成0.0.0.0后 可以多台使用

**Comment by augustus2000** [comment]
> Linux下没问题 把127.0.0.1 改成0.0.0.0后 可以多台使用

之前没说清楚，我的环境是mac OS 10.15.3，其他环境我不清楚

**Comment by kevinfu2** [comment]
windows 平台换成0.0.0.0后无法用，换成本机IP确实可以。谢谢各位，问题已解决
