### ISSUE TITLE
Trojan-QT5 监听8070端口

### ISSUE THREAD

**Issue by Ops-online** [TheWanderingCoel/Trojan-Qt5#77]
版本：V0.0.3 Bug Fix
运行环境：Windows 10 1909 
打开Trojan-QT5时，提示监听8070端口；
如果拒绝此端口，则程序不能使用。
想问下，这个端口的功能是什么？能否变更为其它端口或取消端口的监听？

谢谢

**Comment by TheWanderingCoel** [comment]
8070端口是HTTP服务器，给PAC模式的使用。目前不能更改或取消监听。

**Comment by Ops-online** [comment]
本地服务器类型：SOCKS5
关闭PAC模式，8070端口也是处于监听状态的。

**Comment by TheWanderingCoel** [comment]
嗯，现在逻辑是不管开不开，pac都要监听8070。下个版本修复

**Comment by TheWanderingCoel** [comment]
https://github.com/TheWanderingCoel/Trojan-Qt5/blob/1f1e7cdb0fed95aa3260b7bd3be05842417d7c77/src/main.cpp#L94-L107

**Comment by Ops-online** [comment]
谢谢
