### ISSUE TITLE
按延迟排序的时候能把超时的放在最后面吗

### ISSUE THREAD

**Issue by MatthewDevelop** [TheWanderingCoel/Trojan-Qt5#78]
节点按延迟由低到高排序的时候，超时的放在了最前面，建议放在最后面

**Comment by TheWanderingCoel** [comment]
应该可以实现，有空重写一下排序逻辑

**Comment by TheWanderingCoel** [comment]
![QQ20200315-194602](https://user-images.githubusercontent.com/39617891/76700757-9cafa980-66f5-11ea-9e5e-8b86c9de6ffa.png)

20天了，终于搞定，下个版本推送

**Comment by TimeBye** [comment]
@TheWanderingCoel    大神，在Mac 0.0.4c版本  这个小优化没有更新进来哇？



![image](https://user-images.githubusercontent.com/22651579/77131338-5613d380-6a96-11ea-8923-522a5d1aa52c.png)


![image](https://user-images.githubusercontent.com/22651579/77131363-662bb300-6a96-11ea-908a-a8ffd6835d53.png)

**Comment by TheWanderingCoel** [comment]
点到lock了尴尬，这个004d才会加入

**Comment by TimeBye** [comment]
嘿嘿    好的    期待大神更新  🎉

**Comment by TheWanderingCoel** [comment]
v0.0.4d已完成

**Comment by TimeBye** [comment]
@TheWanderingCoel    大神  v0.0.4d  怎么不发mac的包了  😂😂

**Comment by TheWanderingCoel** [comment]
@TimeBye travis-ci出bug了，一直不构建v0.0.4d
