### ISSUE TITLE
enhance requirement: add right click menu for quick switch node in taskbar icon

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#8]

**Comment by TheWanderingCoel** [comment]
If this feature introduced, I'm afraid I have to limit to only connect one server at the same time.

**Comment by babylife** [comment]
嘿嘿 :) waiting your next release  should be a bug surprise !

**Comment by SplitGemini** [comment]
> If this feature introduced, I'm afraid I have to limit to only connect one server at the same time.

右键里的选项其实也可以设置成多选

**Comment by TheWanderingCoel** [comment]
privoxy监听多个端口关掉并不会释放，现在策略是只能连接一个服务器了

**Comment by TheWanderingCoel** [comment]
Done
