### ISSUE TITLE
谁能给一个macOS的nightly build么?

### ISSUE THREAD

**Issue by ShineUnM** [TheWanderingCoel/Trojan-Qt5#85]
现在的0.0.3FIX用的还是不太顺手，TheWanderingCoel最近更新了不少内容，有人能发一个macOS下的nightly build么？
感谢

**Comment by TheWanderingCoel** [comment]
现在有可能有编译错误，0.0.4快了，就是要实现的featre有点太多了。这issue都关不过来

**Comment by TheWanderingCoel** [comment]
已完成，请等待构建完成后尝试``v0.0.4``
