### ISSUE TITLE
建议：Mac下 Docker里的图标可否改为自动隐藏

### ISSUE THREAD

**Issue by Kenji-Nie** [TheWanderingCoel/Trojan-Qt5#86]
建议：Mac下 Docker里的图标可否改为自动隐藏，谢谢~~~

**Comment by Kenji-Nie** [comment]
建议：Mac下 Docker里的图标可否改为自动隐藏。
还有就是Mac下为什么每次打开都要提示我允许网络连接呢，我已经在防火墙下允许了~~~~~

**Comment by TheWanderingCoel** [comment]
0.0.4将可以在任务栏按最小化隐藏。把应用程序直接放到应用程序文件夹试试？在dmg打开会一直提醒

**Comment by Kenji-Nie** [comment]
谢谢，我试了下，修改Info.plist文件添加
<key>LSUIElement</key>
<string>1</string>
就可以在docker中隐藏了

**Comment by Kenji-Nie** [comment]
<key>LSUIElement</key>
<string>1</string>

**Comment by Kenji-Nie** [comment]
![image](https://user-images.githubusercontent.com/37642562/75238130-78019980-57fb-11ea-8a83-83cca7d06578.png)
![image](https://user-images.githubusercontent.com/37642562/75238141-7b952080-57fb-11ea-846e-f7c44739812e.png)
![image](https://user-images.githubusercontent.com/37642562/75238168-8354c500-57fb-11ea-9f6e-59a0b1f57a7c.png)

**Comment by Kenji-Nie** [comment]
![image](https://user-images.githubusercontent.com/37642562/75238130-78019980-57fb-11ea-8a83-83cca7d06578.png)

**Comment by Kenji-Nie** [comment]
但是能不能设置每次打开的时候自动连接呢，不然虽然自动启动了，但还是不自动连接

**Comment by TheWanderingCoel** [comment]
0.0.4也会加入。0.0.4就不用修改Info.plist了，并且自动开启软件连接服务器

**Comment by Kenji-Nie** [comment]
谢谢~~~，期待0.0.4，不知什么时候能出来呢~~

**Comment by TheWanderingCoel** [comment]
还有好多feature没做完...可能要一点时间

**Comment by Kenji-Nie** [comment]
我的是放应用程序文件夹了，还是会一直提示的，除非把防火墙关了。

**Comment by Kenji-Nie** [comment]
嗯嗯，感谢感谢~~加油加油~~

**Comment by TheWanderingCoel** [comment]
感觉是防火墙的bug还是啥的。我有空研究下

**Comment by Kenji-Nie** [comment]
好像说是没有被Apple认证的问题，好像需要个证书才行

**Comment by TheWanderingCoel** [comment]
开发者证书么？我有是有，但是不能放到ci自动化构建上...

**Comment by Kenji-Nie** [comment]
这个我也不是太懂，不知道是不是这里的原因
![image](https://user-images.githubusercontent.com/37642562/75240337-21965a00-57ff-11ea-9518-e75136f75a28.png)

**Comment by Kenji-Nie** [comment]
![image](https://user-images.githubusercontent.com/37642562/75240416-4559a000-57ff-11ea-98bb-5f808060f0ab.png)

**Comment by Kenji-Nie** [comment]
![image](https://user-images.githubusercontent.com/37642562/75240469-573b4300-57ff-11ea-8b81-584dabc7d12c.png)

**Comment by Kenji-Nie** [comment]
这个我也不是太懂，在防火墙设置里有个允许已下载签名软件连接网络

**Comment by TheWanderingCoel** [comment]
v0.0.4d已完成
