### ISSUE TITLE
error when connect second node when another already connected

### ISSUE THREAD

**Issue by babylife** [TheWanderingCoel/Trojan-Qt5#9]
Maybe should disconnect the connected node before try to connect the new node. 
![QQ截图20200218131120](https://user-images.githubusercontent.com/31977161/74705916-714db200-5250-11ea-8097-3152a785a2b5.png)

**Comment by babylife** [comment]
the workaround current is disconnect the connected node first ,then connect anothr node.

**Comment by TheWanderingCoel** [comment]
You have to set a different ``http port``. You can't listen the same port two times.

**Comment by TheWanderingCoel** [comment]
![WX20200218-131812](https://user-images.githubusercontent.com/39617891/74706141-22544c80-5251-11ea-9f48-93d1f4f4fa4f.png)
Try to set these ports to different value for another server, like ``1082`` and ``1083``

**Comment by babylife** [comment]
I see. change port is a quick fix way. 
BWT,i think it is a windows OS LAN level proxy which  adds to windows internet LAN settings. so it will not use 2 nodes at same time. is it make sense to disconnect first the connect new node? or maybe some 3rd software can manually different node to connect. 
maybe add a checkbox to control if we only connect one node. 
thank you !

**Comment by TheWanderingCoel** [comment]
Yeah. You can only use one server at the same(the last one you connect). In some browser(eg. firefox), or some applications(eg. telegram), you can manually set the proxy.

**Comment by TheWanderingCoel** [comment]
If the local ``socksPort`` or ``httpPort`` is in use, the server won't connect unless you free those ports or change to another port
