### ISSUE TITLE
本地局域网内HTTP代理无法使用

### ISSUE THREAD

**Issue by Michany** [TheWanderingCoel/Trojan-Qt5#92]
问题描述：想要在手机上设置HTTP代理连同一局域网的电脑Trojan程序以上网，但是配置好后连接无任何反应。所有配置基本都是默认。

**电脑端**(Windows)
局域网ip: 192.168.1.111
Trojan设置:
- 本地地址: 127.0.0.1
- 本地端口: 1080
- 本地HTTP端口: 1081

**手机端**(iOS)
局域网ip: 192.168.1.105
Wifi设置：
- HTTP Proxy: 192.168.1.111
- Port: 1081

电脑端cmd输入`netstat -aon|findstr "1081"`后，的确有监听1081端口的程序，根据pid找到的对应进程名privoxy.exe

**Comment by TheWanderingCoel** [comment]
请将本地地址设置成192.168.1.111

**Comment by Michany** [comment]
成了，厉害！
