### ISSUE TITLE
toolbar隐藏后如何重新设置显示出来？

### ISSUE THREAD

**Issue by xenialaw08** [TheWanderingCoel/Trojan-Qt5#97]
错手右键把toolbar设置隐藏了，试过所有设置都无法调整显示回来。请问可以如何解决？
PS：toolbar的按钮可以自定义增减吗？

**Comment by boyandtoy** [comment]
Yes, Maybe the same situation that I encountered, When I select the choice "hide the toolbar" then it can not show anymore.

**Comment by TheWanderingCoel** [comment]
右键一次点显示应该回来吧。实在不行在设置里关闭使用原生那个

**Comment by xenialaw08** [comment]
> 右键一次点显示应该回来吧。实在不行在设置里关闭使用原生那个

这些方法我都试过，无法重新显示出来。
[附图](http://www.yeahyo.cn/img/temporary/WX20200226.png)

**Comment by xenialaw08** [comment]
> Yes, Maybe the same situation that I encountered, When I select the choice "hide the toolbar" then it can not show anymore.

yep~ the same situation

**Comment by TheWanderingCoel** [comment]
导出所有服务器后把``~/.config/trojan-qt5``这个文件夹删了应该会恢复

**Comment by xenialaw08** [comment]
> 导出所有服务器后把`~/.config/trojan-qt5`这个文件夹删了应该会恢复

我之前删了其他系统文件路径都无法恢复，终于这个方法搞定了。谢谢！
