### ISSUE TITLE
导出导入结果中缺失localhttpport 参数

### ISSUE THREAD

**Issue by fyuan1316** [TheWanderingCoel/Trojan-Qt5#98]
bug / feature 
bug？
version：V0.0.3 Bug Fix
os ： macOS High Sierra  10.13.6

amazing work！ 
从v2ray 过来的，总体感觉很好用。感谢！发现一些小问题，不知是bug 还是 wip feature？

- 导出的gui-config.json 缺失 localhttpport

 ![image](https://user-images.githubusercontent.com/42265657/75342773-08121280-58d2-11ea-9f42-1f057c9681f7.png)

-  ps：刚接触这块儿一些细节不太了解，我看到代码实现里local port 和local http port 没有放在ConnectionTableModel 里和其他参数一起处理。这里有别的考虑么？

**Comment by TheWanderingCoel** [comment]
因为从ss-qt搬过来后加的http port就没有修改，0.0.4惠修改一下这部分的东西。感谢反馈

**Comment by TheWanderingCoel** [comment]
已完成，请等待构建完成后尝试``v0.0.4``
