### ISSUE TITLE
自动连接不起作用

### ISSUE THREAD

**Issue by raylapse** [TheWanderingCoel/Trojan-Qt5#99]
win10，设置为随系统自动启动，指定某个profile里的参数为自动自动连接
但是trojan是启动了，但是图标是灰色，必须手动再次点连接才行，请帮忙看看。

附带另外一个问题，用trojan后google photos使用的google backup and sync不能连接了，以前用SS是全局代理是可以的。使用这个工具应该也很多吧，望修复！我查了下貌似这个工具支持的pac不能有端口号，目前trojan用的是8070还不能改，能不能修正成端口号80？或者给个参数使用户可以改？

**Comment by TheWanderingCoel** [comment]
自动化是bug,0.0.4修复。端口号也会在0.0.4让用户自定义。google photos我要研究下

**Comment by TheWanderingCoel** [comment]
已完成，请等待构建完成后尝试``v0.0.4``

**Comment by raylapse** [comment]
感谢如此快速的修正，赞一个
我试了下80端口google photos还是不行，搞不懂了，反正以前SS是可以的，技术上不太清楚ss的pac模式和trojan有啥不同，我粗浅的看只是pac地址的不同，ss的pac地址貌似是有加密的？

另外反应个小问题，菜单栏在4k屏下缩放200%不起作用，依然很小

**Comment by TheWanderingCoel** [comment]
试试手动添加谷歌photos的服务器到用户规则？pac必须重启软件才能生效。4k目前没啥办法...
